#define XMLGUI_DISTRIBUTION_TEXT "${XMLGUI_DISTRIBUTION_TEXT}"
#define XMLGUI_COMPILING_OS "${CMAKE_SYSTEM}"
#define XMLGUI_COMPILER_VERSION "${XMLGUI_COMPILER_VERSION}"

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define KF5_LIBEXEC_INSTALL_DIR "${KF5_LIBEXEC_INSTALL_DIR}"

#include <KoConfig.h>
