######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 14 14:28:04 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stroke.h
SOURCES += stroke.cpp
