######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 19:28:06 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h stroke.h
SOURCES += main.cpp MyWidget.cpp stroke.cpp
