<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Krita">
  <Actions category="Settings">
    <text>Settings</text>
    <Action name="dbexplorer">
      <icon></icon>
      <text>&amp;Explore Resources Cache Database...</text>
      <whatsThis>Resources Cache Database</whatsThis>
      <toolTip>Resources Cache Database</toolTip>
      <iconText>Resources Cache Database</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
