<Actions version="1" name="KisToolSelectPolygonal">
 <Action iconText="Reset Foreground and Background Color" shortcut="D" toolTip="Reset Foreground and Background Color" icon="" whatsThis="" statusTip="" name="reset_fg_bg" isCheckable="false" text="Reset Foreground and Background Color" defaultShortcut="D"/>
 <Action iconText="Swap Foreground and Background Color" shortcut="X" toolTip="Swap Foreground and Background Color" icon="" whatsThis="" statusTip="" name="toggle_fg_bg" isCheckable="false" text="Swap Foreground and Background Color" defaultShortcut="X"/>
 <Action iconText="Decrease Brush Size" shortcut="[" toolTip="Decrease Brush Size" icon="" whatsThis="" statusTip="" name="decrease_brush_size" isCheckable="false" text="Decrease Brush Size" defaultShortcut="["/>
 <Action iconText="Increase Brush Size" shortcut="]" toolTip="Increase Brush Size" icon="" whatsThis="" statusTip="" name="increase_brush_size" isCheckable="false" text="Increase Brush Size" defaultShortcut="]"/>
</Actions>
