/* config-krita.h.  Generated by cmake from config-krita.h.cmake */

/* Defines if you have GL (Mesa, OpenGL, ...) */
#cmakedefine HAVE_OPENGL 1

/* Define if you have the X11 Input Extension */
#cmakedefine HAVE_XINPUTEXT 1

/* Define if you have powf */
#cmakedefine HAVE_POWF 1

