<?xml version="1.0"?>
<Actions name="krita">
    <Action name="save_incremental_version" icon="" text="Save Incremental &amp;Version" whatsThis="" toolTip="Save Incremental Version" iconText="Save Incremental Version" shortcut="Ctrl+Alt+S" defaultShortcut="Ctrl+Alt+S" isCheckable="false" statusTip=""/>
    <Action name="save_incremental_backup" icon="" text="Save Incremental Backup" whatsThis="" toolTip="Save Incremental Backup" iconText="Save Incremental Backup" shortcut="F4" defaultShortcut="F4" isCheckable="false" statusTip=""/>
    <Action name="tablet_debugger" icon="" text="Toggle Tablet Debugger" whatsThis="" toolTip="Toggle Tablet Debugger" iconText="Toggle Tablet Debugger" shortcut="Ctrl+Shift+T" defaultShortcut="Ctrl+Shift+T" isCheckable="false" statusTip=""/>
    <Action name="create_t`emplate" icon="" text="&amp;Create Template From Image..." whatsThis="" toolTip="Create Template From Image" iconText="Create Template From Image" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="open_resources_directory" icon="" text="Open Resources Folder" whatsThis="Opens a file browser at the location Krita saves resources such as brushes to." toolTip="Opens a file browser at the location Krita saves resources such as brushes to." iconText="Open Resources Folder" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotate_canvas_right" icon="" text="Rotate Canvas Right" whatsThis="" toolTip="Rotate Canvas Right" iconText="Rotate Canvas Right" shortcut="Ctrl+]" defaultShortcut="Ctrl+]" isCheckable="false" statusTip=""/>
    <Action name="rotate_canvas_left" icon="" text="Rotate Canvas Left" whatsThis="" toolTip="Rotate Canvas Left" iconText="Rotate Canvas Left" shortcut="Ctrl+[" defaultShortcut="Ctrl+[" isCheckable="false" statusTip=""/>
    <Action name="wrap_around_mode" icon="" text="Wrap Around Mode" whatsThis="" toolTip="Wrap Around Mode" iconText="Wrap Around Mode" shortcut="W" defaultShortcut="W" isCheckable="false" statusTip=""/>
    <Action name="showStatusBar" icon="" text="Hide Status Bar" whatsThis="" toolTip="Shows or hides the status bar" iconText="Hide Status Bar" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="view_show_just_the_canvas" icon="" text="Show Canvas Only" whatsThis="" toolTip="Shows just the canvas or the whole window" iconText="Show Canvas Only" shortcut="Tab" defaultShortcut="Tab" isCheckable="false" statusTip=""/>
    <Action name="edit_blacklist_cleanup" icon="" text="Cleanup removed files..." whatsThis="" toolTip="Cleanup removed files" iconText="Cleanup removed files" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="filter_apply_again" icon="" text="Apply Filter Again" whatsThis="" toolTip="Apply Filter Again" iconText="Apply Filter Again" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="color_filters" icon="" text="Colors" whatsThis="" toolTip="Colors" iconText="Colors" shortcut="" defaultShortcut="Ctrl+F" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_colortoalpha" icon="" text="&amp;Color to Alpha..." whatsThis="" toolTip="Color to Alpha" iconText="Color to Alpha" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="edge_filters" icon="" text="Edge Detection" whatsThis="" toolTip="Edge Detection" iconText="Edge Detection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_top edge detections" icon="" text="Top Edge Detection" whatsThis="" toolTip="Top Edge Detection" iconText="Top Edge Detection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="artistic_filters" icon="" text="Artistic" whatsThis="" toolTip="Artistic" iconText="Artistic" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_indexcolors" icon="" text="&amp;Index Colors..." whatsThis="" toolTip="Index Colors" iconText="Index Colors" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="emboss_filters" icon="" text="Emboss" whatsThis="" toolTip="Emboss" iconText="Emboss" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss horizontal only" icon="" text="Emboss Horizontal Only" whatsThis="" toolTip="Emboss Horizontal Only" iconText="Emboss Horizontal Only" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="adjust_filters" icon="" text="Adjust" whatsThis="" toolTip="Adjust" iconText="Adjust" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_dodge" icon="" text="Dodge" whatsThis="" toolTip="Dodge" iconText="Dodge" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="enhance_filters" icon="" text="Enhance" whatsThis="" toolTip="Enhance" iconText="Enhance" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_sharpen" icon="" text="&amp;Sharpen" whatsThis="" toolTip="Sharpen" iconText="Sharpen" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_burn" icon="" text="Burn" whatsThis="" toolTip="Burn" iconText="Burn" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_mean removal" icon="" text="&amp;Mean Removal" whatsThis="" toolTip="Mean Removal" iconText="Mean Removal" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="blur_filters" icon="" text="Blur" whatsThis="" toolTip="Blur" iconText="Blur" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_gaussian blur" icon="" text="&amp;Gaussian Blur..." whatsThis="" toolTip="Gaussian Blur" iconText="Gaussian Blur" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss all directions" icon="" text="Emboss in All Directions" whatsThis="" toolTip="Emboss in All Directions" iconText="Emboss in All Directions" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="map_filters" icon="" text="Map" whatsThis="" toolTip="Map" iconText="Map" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_smalltiles" icon="" text="&amp;Small Tiles..." whatsThis="" toolTip="Small Tiles" iconText="Small Tiles" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_levels" icon="" text="&amp;Levels..." whatsThis="" toolTip="Levels" iconText="Levels" shortcut="Ctrl+L" defaultShortcut="Ctrl+L" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_sobel" icon="" text="&amp;Sobel..." whatsThis="" toolTip="Sobel" iconText="Sobel" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="other_filters" icon="" text="Other" whatsThis="" toolTip="Other" iconText="Other" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_wave" icon="" text="&amp;Wave..." whatsThis="" toolTip="Wave" iconText="Wave" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_motion blur" icon="" text="&amp;Motion Blur..." whatsThis="" toolTip="Motion Blur" iconText="Motion Blur" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_perchannel" icon="" text="&amp;Color Adjustment curves..." whatsThis="" toolTip="Color Adjustment curves" iconText="Color Adjustment curves" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_pixelize" icon="" text="&amp;Pixelize..." whatsThis="" toolTip="Pixelize" iconText="Pixelize" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss laplascian" icon="" text="Emboss (Laplacian)" whatsThis="" toolTip="Emboss (Laplacian)" iconText="Emboss (Laplacian)" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_left edge detections" icon="" text="Left Edge Detection" whatsThis="" toolTip="Left Edge Detection" iconText="Left Edge Detection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_blur" icon="" text="&amp;Blur..." whatsThis="" toolTip="Blur" iconText="Blur" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_raindrops" icon="" text="&amp;Raindrops..." whatsThis="" toolTip="Raindrops" iconText="Raindrops" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_bottom edge detections" icon="" text="Bottom Edge Detection" whatsThis="" toolTip="Bottom Edge Detection" iconText="Bottom Edge Detection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_noise" icon="" text="&amp;Random Noise..." whatsThis="" toolTip="Random Noise" iconText="Random Noise" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_brightnesscontrast" icon="" text="&amp;Brightness/Contrast curve..." whatsThis="" toolTip="Brightness/Contrast curve" iconText="Brightness/Contrast curve" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_colorbalance" icon="" text="&amp;Color Balance.." whatsThis="" toolTip="Color Balance.." iconText="Color Balance.." shortcut="Ctrl+B" defaultShortcut="Ctrl+B" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_phongbumpmap" icon="" text="&amp;PhongBumpmap..." whatsThis="" toolTip="PhongBumpmap" iconText="PhongBumpmap" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_desaturate" icon="" text="&amp;Desaturate" whatsThis="" toolTip="Desaturate" iconText="Desaturate" shortcut="Ctrl+Shift+U" defaultShortcut="Ctrl+Shift+U" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_colortransfer" icon="" text="&amp;Color Transfer..." whatsThis="" toolTip="Color Transfer" iconText="Color Transfer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss vertical only" icon="" text="Emboss Vertical Only" whatsThis="" toolTip="Emboss Vertical Only" iconText="Emboss Vertical Only" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_lens blur" icon="" text="&amp;Lens Blur..." whatsThis="" toolTip="Lens Blur" iconText="Lens Blur" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_minimize" icon="" text="M&amp;inimize Channel" whatsThis="" toolTip="Minimize Channel" iconText="Minimize Channel" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_maximize" icon="" text="M&amp;aximize Channel" whatsThis="" toolTip="Maximize Channel" iconText="Maximize Channel" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_oilpaint" icon="" text="&amp;Oilpaint..." whatsThis="" toolTip="Oilpaint" iconText="Oilpaint" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_right edge detections" icon="" text="Right Edge Detection" whatsThis="" toolTip="Right Edge Detection" iconText="Right Edge Detection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_invert" icon="" text="&amp;Invert" whatsThis="" toolTip="Invert" iconText="Invert" shortcut="Ctrl+I" defaultShortcut="Ctrl+I" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_autocontrast" icon="" text="&amp;Auto Contrast" whatsThis="" toolTip="Auto Contrast" iconText="Auto Contrast" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_roundcorners" icon="" text="&amp;Round Corners..." whatsThis="" toolTip="Round Corners" iconText="Round Corners" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_unsharp" icon="" text="&amp;Unsharp Mask..." whatsThis="" toolTip="Unsharp Mask" iconText="Unsharp Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss" icon="" text="&amp;Emboss with Variable Depth..." whatsThis="" toolTip="Emboss with Variable Depth" iconText="Emboss with Variable Depth" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_emboss horizontal and vertical" icon="" text="Emboss Horizontal &amp;&amp; Vertical" whatsThis="" toolTip="Emboss Horizontal &amp; Vertical" iconText="Emboss Horizontal &amp; Vertical" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_randompick" icon="" text="&amp;Random Pick..." whatsThis="" toolTip="Random Pick" iconText="Random Pick" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_gaussiannoisereducer" icon="" text="&amp;Gaussian Noise Reduction..." whatsThis="" toolTip="Gaussian Noise Reduction" iconText="Gaussian Noise Reduction" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_posterize" icon="" text="&amp;Posterize..." whatsThis="" toolTip="Posterize" iconText="Posterize" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_waveletnoisereducer" icon="" text="&amp;Wavelet Noise Reducer..." whatsThis="" toolTip="Wavelet Noise Reducer" iconText="Wavelet Noise Reducer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="krita_filter_hsvadjustment" icon="" text="&amp;HSV Adjustment..." whatsThis="" toolTip="HSV Adjustment" iconText="HSV Adjustment" shortcut="Ctrl+U" defaultShortcut="Ctrl+U" isCheckable="false" statusTip=""/>
    <Action name="edit_cut" icon="edit-cut" text="Cu&amp;t" whatsThis="" toolTip="Cut selection to clipboard" iconText="Cut" shortcut="Ctrl+X; Shift+Del" defaultShortcut="Ctrl+X; Shift+Del" isCheckable="false" statusTip=""/>
    <Action name="edit_copy" icon="edit-copy" text="&amp;Copy" whatsThis="" toolTip="Copy selection to clipboard" iconText="Copy" shortcut="Ctrl+C; Ctrl+Ins" defaultShortcut="Ctrl+C; Ctrl+Ins" isCheckable="false" statusTip=""/>
    <Action name="edit_paste" icon="edit-paste" text="&amp;Paste" whatsThis="" toolTip="Paste clipboard content" iconText="Paste" shortcut="Ctrl+V; Shift+Ins" defaultShortcut="Ctrl+V; Shift+Ins" isCheckable="false" statusTip=""/>
    <Action name="paste_new" icon="" text="Paste into &amp;New Image" whatsThis="" toolTip="Paste into New Image" iconText="Paste into New Image" shortcut="Ctrl+Shift+N" defaultShortcut="Ctrl+Shift+N" isCheckable="false" statusTip=""/>
    <Action name="paste_at" icon="" text="Paste at cursor" whatsThis="" toolTip="Paste at cursor" iconText="Paste at cursor" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="copy_merged" icon="" text="Copy merged" whatsThis="" toolTip="Copy merged" iconText="Copy merged" shortcut="Ctrl+Shift+C" defaultShortcut="Ctrl+Shift+C" isCheckable="false" statusTip=""/>
    <Action name="select_all" icon="edit-select-all" text="Select &amp;All" whatsThis="" toolTip="Select All" iconText="Select All" shortcut="Ctrl+A" defaultShortcut="Ctrl+A" isCheckable="false" statusTip=""/>
    <Action name="deselect" icon="edit-select-all" text="Deselect" whatsThis="" toolTip="Deselect" iconText="Deselect" shortcut="Ctrl+Shift+A" defaultShortcut="Ctrl+Shift+A" isCheckable="false" statusTip=""/>
    <Action name="clear" icon="edit-clear" text="Clear" whatsThis="" toolTip="Clear" iconText="Clear" shortcut="Del" defaultShortcut="Del" isCheckable="false" statusTip=""/>
    <Action name="reselect" icon="" text="&amp;Reselect" whatsThis="" toolTip="Reselect" iconText="Reselect" shortcut="Ctrl+Shift+D" defaultShortcut="Ctrl+Shift+D" isCheckable="false" statusTip=""/>
    <Action name="invert" icon="" text="&amp;Invert Selection" whatsThis="" toolTip="foo" iconText="Invert Selection" shortcut="Ctrl+Shift+I" defaultShortcut="Ctrl+Shift+I" isCheckable="false" statusTip=""/>
    <Action name="copy_selection_to_new_layer" icon="" text="Copy Selection to New Layer" whatsThis="" toolTip="Copy Selection to New Layer" iconText="Copy Selection to New Layer" shortcut="Ctrl+Alt+J" defaultShortcut="Ctrl+Alt+J" isCheckable="false" statusTip=""/>
    <Action name="cut_selection_to_new_layer" icon="" text="Cut Selection to New Layer" whatsThis="" toolTip="Cut Selection to New Layer" iconText="Cut Selection to New Layer" shortcut="Ctrl+Shift+J" defaultShortcut="Ctrl+Shift+J" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_foreground_color" icon="" text="Fill with Foreground Color" whatsThis="" toolTip="Fill with Foreground Color" iconText="Fill with Foreground Color" shortcut="Shift+Backspace" defaultShortcut="Shift+Backspace" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_background_color" icon="" text="Fill with Background Color" whatsThis="" toolTip="Fill with Background Color" iconText="Fill with Background Color" shortcut="Backspace" defaultShortcut="Backspace" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_pattern" icon="" text="Fill with Pattern" whatsThis="" toolTip="Fill with Pattern" iconText="Fill with Pattern" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_foreground_color_opacity" icon="" text="Fill with Foreground Color (Opacity)" whatsThis="" toolTip="Fill with Foreground Color (Opacity)" iconText="Fill with Foreground Color (Opacity)" shortcut="Ctrl+Shift+Backspace" defaultShortcut="Ctrl+Shift+Backspace" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_background_color_opacity" icon="" text="Fill with Background Color (Opacity)" whatsThis="" toolTip="Fill with Background Color (Opacity)" iconText="Fill with Background Color (Opacity)" shortcut="Ctrl+Backspace" defaultShortcut="Ctrl+Backspace" isCheckable="false" statusTip=""/>
    <Action name="fill_selection_pattern_opacity" icon="" text="Fill with Pattern (Opacity)" whatsThis="" toolTip="Fill with Pattern (Opacity)" iconText="Fill with Pattern (Opacity)" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="stroke_shapes" icon="" text="Stro&amp;ke selected shapes" whatsThis="" toolTip="Stroke selected shapes" iconText="Stroke selected shapes" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="toggle_display_selection" icon="" text="Display Selection" whatsThis="" toolTip="Display Selection" iconText="Display Selection" shortcut="Ctrl+H" defaultShortcut="Ctrl+H" isCheckable="true" statusTip=""/>
    <Action name="resizeimagetoselection" icon="" text="Size Canvas to Size of Selection" whatsThis="" toolTip="Size Canvas to Size of Selection" iconText="Size Canvas to Size of Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_to_vector_selection" icon="" text="&amp;Convert to Vector Selection" whatsThis="" toolTip="Convert to Vector Selection" iconText="Convert to Vector Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_shapes_to_vector_selection" icon="" text="Convert &amp;Shapes to Vector Selection" whatsThis="" toolTip="Convert Shapes to Vector Selection" iconText="Convert Shapes to Vector Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="toggle-selection-overlay-mode" icon="" text="&amp;Toggle Selection Display Mode" whatsThis="" toolTip="Toggle Selection Display Mode" iconText="Toggle Selection Display Mode" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="merge_selected_layers" icon="" text="&amp;Merge Selected Layers" whatsThis="" toolTip="Merge Selected Layers" iconText="Merge Selected Layers" shortcut="Ctrl+Alt+E" defaultShortcut="Ctrl+Alt+E" isCheckable="false" statusTip=""/>
    <Action name="flatten_image" icon="" text="&amp;Flatten image" whatsThis="" toolTip="Flatten image" iconText="Flatten image" shortcut="Ctrl+Shift+E" defaultShortcut="Ctrl+Shift+E" isCheckable="false" statusTip=""/>
    <Action name="merge_layer" icon="" text="&amp;Merge with Layer Below" whatsThis="" toolTip="Merge with Layer Below" iconText="Merge with Layer Below" shortcut="Ctrl+E" defaultShortcut="Ctrl+E" isCheckable="false" statusTip=""/>
    <Action name="flatten_layer" icon="" text="&amp;Flatten Layer" whatsThis="" toolTip="Flatten Layer" iconText="Flatten Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="RenameCurrentLayer" icon="" text="Rename current layer" whatsThis="" toolTip="Rename current layer" iconText="Rename current layer" shortcut="F2" defaultShortcut="F2" isCheckable="false" statusTip=""/>
    <Action name="rasterize_layer" icon="" text="Rasterize Layer" whatsThis="" toolTip="Rasterize Layer" iconText="Rasterize Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="save_groups_as_images" icon="document-save" text="Save Group Layers..." whatsThis="" toolTip="Save Group Layers" iconText="Save Group Layers" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="resizeimagetolayer" icon="" text="Size Canvas to Size of Current Layer" whatsThis="" toolTip="Size Canvas to Size of Current Layer" iconText="Size Canvas to Size of Current Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="trim_to_image" icon="light_trim-to-image" text="Trim to Image Size" whatsThis="" toolTip="Trim to Image Size" iconText="Trim to Image Size" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="mirrorNodeX" icon="light_symmetry-horizontal" text="Mirror Layer Horizontally" whatsThis="" toolTip="Mirror Layer Horizontally" iconText="Mirror Layer Horizontally" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="mirrorNodeY" icon="light_symmetry-vertical" text="Mirror Layer Vertically" whatsThis="" toolTip="Mirror Layer Vertically" iconText="Mirror Layer Vertically" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="activateNextLayer" icon="" text="Activate next layer" whatsThis="" toolTip="Activate next layer" iconText="Activate next layer" shortcut="PgUp" defaultShortcut="PgUp" isCheckable="false" statusTip=""/>
    <Action name="activatePreviousLayer" icon="" text="Activate previous layer" whatsThis="" toolTip="Activate previous layer" iconText="Activate previous layer" shortcut="PgDown" defaultShortcut="PgDown" isCheckable="false" statusTip=""/>
    <Action name="save_node_as_image" icon="document-save" text="Save Layer/Mask..." whatsThis="" toolTip="Save Layer/Mask" iconText="Save Layer/Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="duplicatelayer" icon="edit-copy" text="&amp;Duplicate Layer or Mask" whatsThis="" toolTip="Duplicate Layer or Mask" iconText="Duplicate Layer or Mask" shortcut="Ctrl+J" defaultShortcut="Ctrl+J" isCheckable="false" statusTip=""/>
    <Action name="add_new_paint_layer" icon="light_document-new" text="&amp;Paint Layer" whatsThis="" toolTip="Paint Layer" iconText="Paint Layer" shortcut="Ins" defaultShortcut="Ins" isCheckable="false" statusTip=""/>
    <Action name="add_new_group_layer" icon="folder-new" text="&amp;Group Layer" whatsThis="" toolTip="Group Layer" iconText="Group Layer" shortcut="Ctrl+G" defaultShortcut="Ctrl+G" isCheckable="false" statusTip=""/>
    <Action name="add_new_clone_layer" icon="edit-copy" text="&amp;Clone Layer" whatsThis="" toolTip="Clone Layer" iconText="Clone Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_shape_layer" icon="bookmark-new" text="&amp;Vector Layer" whatsThis="" toolTip="Vector Layer" iconText="Vector Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_adjustment_layer" icon="view-filter" text="&amp;Filter Layer..." whatsThis="" toolTip="Filter Layer" iconText="Filter Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_fill_layer" icon="krita_tool_color_fill" text="&amp;Fill Layer..." whatsThis="" toolTip="Fill Layer" iconText="Fill Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_file_layer" icon="document-open" text="&amp;File Layer..." whatsThis="" toolTip="File Layer" iconText="File Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_transparency_mask" icon="edit-copy" text="&amp;Transparency Mask" whatsThis="" toolTip="Transparency Mask" iconText="Transparency Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_filter_mask" icon="bookmarks" text="&amp;Filter Mask..." whatsThis="" toolTip="Filter Mask" iconText="Filter Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_transform_mask" icon="bookmarks" text="&amp;Transform Mask..." whatsThis="" toolTip="Transform Mask" iconText="Transform Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="add_new_selection_mask" icon="edit-paste" text="&amp;Local Selection" whatsThis="" toolTip="Local Selection" iconText="Local Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_to_paint_layer" icon="document-new" text="to &amp;Paint Layer" whatsThis="" toolTip="to Paint Layer" iconText="to Paint Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_to_selection_mask" icon="edit-paste" text="to &amp;Selection Mask" whatsThis="" toolTip="to Selection Mask" iconText="to Selection Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_to_filter_mask" icon="bookmarks" text="to &amp;Filter Mask..." whatsThis="" toolTip="to Filter Mask" iconText="to Filter Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="convert_to_transparency_mask" icon="edit-copy" text="to &amp;Transparency Mask" whatsThis="" toolTip="to Transparency Mask" iconText="to Transparency Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="isolate_layer" icon="view-filter" text="&amp;Isolate Layer" whatsThis="" toolTip="Isolate Layer" iconText="Isolate Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="split_alpha_into_mask" icon="edit-copy" text="Alpha into Mask" whatsThis="" toolTip="Alpha into Mask" iconText="Alpha into Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="split_alpha_write" icon="transparency-enabled" text="Write as Alpha" whatsThis="" toolTip="Write as Alpha" iconText="Write as Alpha" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="split_alpha_save_merged" icon="document-save" text="Save Merged..." whatsThis="" toolTip="Save Merged" iconText="Save Merged" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_layer_from_file" icon="" text="I&amp;mport Layer..." whatsThis="" toolTip="Import Layer" iconText="Import Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="image_properties" icon="document-properties" text="Properties..." whatsThis="" toolTip="Properties" iconText="Properties" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_layer_as_paint_layer" icon="document-new" text="as Paint Layer..." whatsThis="" toolTip="as Paint Layer" iconText="as Paint Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_layer_as_transparency_mask" icon="edit-copy" text="as Transparency Mask..." whatsThis="" toolTip="as Transparency Mask" iconText="as Transparency Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_layer_as_filter_mask" icon="bookmarks" text="as Filter Mask..." whatsThis="" toolTip="as Filter Mask" iconText="as Filter Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_layer_as_selection_mask" icon="edit-paste" text="as Selection Mask..." whatsThis="" toolTip="as Selection Mask" iconText="as Selection Mask" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="image_color" icon="format-stroke-color" text="Image Background Color and Transparency..." whatsThis="" toolTip="Change the background color of the image" iconText="Image Background Color and Transparency" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="view_grid" icon="view-grid" text="Show Grid" whatsThis="" toolTip="Show Grid" iconText="Show Grid" shortcut="Ctrl+Shift+'" defaultShortcut="Ctrl+Shift+'" isCheckable="false" statusTip=""/>
    <Action name="view_snap_to_grid" icon="" text="Snap To Grid" whatsThis="" toolTip="Snap To Grid" iconText="Snap To Grid" shortcut="Ctrl+Shift+;" defaultShortcut="Ctrl+Shift+;" isCheckable="false" statusTip=""/>
    <Action name="view_toggle_perspective_grid" icon="" text="Show Perspective Grid" whatsThis="" toolTip="Show Perspective Grid" iconText="Show Perspective Grid" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="view_clear_perspective_grid" icon="" text="Clear Perspective Grid" whatsThis="" toolTip="Clear Perspective Grid" iconText="Clear Perspective Grid" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="view_toggle_painting_assistants" icon="" text="Hide Painting Assistants" whatsThis="" toolTip="Hide Painting Assistants" iconText="Hide Painting Assistants" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="view_toggle_assistant_previews" icon="" text="Show Assistant Previews" whatsThis="" toolTip="Show Assistant Previews" iconText="Show Assistant Previews" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="make_brush_color_lighter" icon="" text="Make brush color lighter" whatsThis="" toolTip="Make brush color lighter" iconText="Make brush color lighter" shortcut="L" defaultShortcut="L" isCheckable="false" statusTip=""/>
    <Action name="make_brush_color_darker" icon="" text="Make brush color darker" whatsThis="" toolTip="Make brush color darker" iconText="Make brush color darker" shortcut="H" defaultShortcut="K" isCheckable="false" statusTip=""/>
    <Action name="increase_opacity" icon="" text="Increase opacity" whatsThis="" toolTip="Increase opacity" iconText="Increase opacity" shortcut="O" defaultShortcut="O" isCheckable="false" statusTip=""/>
    <Action name="decrease_opacity" icon="" text="Decrease opacity" whatsThis="" toolTip="Decrease opacity" iconText="Decrease opacity" shortcut="I" defaultShortcut="I" isCheckable="false" statusTip=""/>
    <Action name="mirror_canvas" icon="" text="Mirror View" whatsThis="" toolTip="Mirror View" iconText="Mirror View" shortcut="M" defaultShortcut="M" isCheckable="false" statusTip=""/>
    <Action name="patterns" icon="" text="&amp;Patterns" whatsThis="" toolTip="Patterns" iconText="Patterns" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="gradients" icon="" text="&amp;Gradients" whatsThis="" toolTip="Gradients" iconText="Gradients" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="dual" icon="" text="&amp;Color" whatsThis="" toolTip="Color" iconText="Color" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="erase_action" icon="eraser-toggle" text="Set eraser mode" whatsThis="" toolTip="Set eraser mode" iconText="Set eraser mode" shortcut="E" defaultShortcut="E" isCheckable="false" statusTip=""/>
    <Action name="reload_preset_action" icon="reload_preset" text="Reload Original Preset" whatsThis="" toolTip="Reload Original Preset" iconText="Reload Original Preset" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="preserve_alpha" icon="transparency-unlocked" text="Preserve Alpha" whatsThis="" toolTip="Preserve Alpha" iconText="Preserve Alpha" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="hmirror_action" icon="light_symmetry-horizontal" text="Set horizontal mirror mode" whatsThis="" toolTip="Set horizontal mirror mode" iconText="Set horizontal mirror mode" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="vmirror_action" icon="light_symmetry-vertical" text="Set vertical mirror mode" whatsThis="" toolTip="Set vertical mirror mode" iconText="Set vertical mirror mode" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="Next Blending Mode" icon="" text="Next Blending Mode" whatsThis="" toolTip="Next Blending Mode" iconText="Next Blending Mode" shortcut="Alt+Shift++" defaultShortcut="Alt+Shift++" isCheckable="false" statusTip=""/>
    <Action name="Previous Blending Mode" icon="" text="Previous Blending Mode" whatsThis="" toolTip="Previous Blending Mode" iconText="Previous Blending Mode" shortcut="Alt+Shift+-" defaultShortcut="Alt+Shift+-" isCheckable="false" statusTip=""/>
    <Action name="Select Normal Blending Mode" icon="" text="Select Normal Blending Mode" whatsThis="" toolTip="Select Normal Blending Mode" iconText="Select Normal Blending Mode" shortcut="Alt+Shift+N" defaultShortcut="Alt+Shift+N" isCheckable="false" statusTip=""/>
    <Action name="Select Dissolve Blending Mode" icon="" text="Select Dissolve Blending Mode" whatsThis="" toolTip="Select Dissolve Blending Mode" iconText="Select Dissolve Blending Mode" shortcut="Alt+Shift+I" defaultShortcut="Alt+Shift+I" isCheckable="false" statusTip=""/>
    <Action name="Select Behind Blending Mode" icon="" text="Select Behind Blending Mode" whatsThis="" toolTip="Select Behind Blending Mode" iconText="Select Behind Blending Mode" shortcut="Alt+Shift+Q" defaultShortcut="Alt+Shift+Q" isCheckable="false" statusTip=""/>
    <Action name="Select Clear Blending Mode" icon="" text="Select Clear Blending Mode" whatsThis="" toolTip="Select Clear Blending Mode" iconText="Select Clear Blending Mode" shortcut="Alt+Shift+R" defaultShortcut="Alt+Shift+R" isCheckable="false" statusTip=""/>
    <Action name="Select Darken Blending Mode" icon="" text="Select Darken Blending Mode" whatsThis="" toolTip="Select Darken Blending Mode" iconText="Select Darken Blending Mode" shortcut="Alt+Shift+K" defaultShortcut="Alt+Shift+K" isCheckable="false" statusTip=""/>
    <Action name="Select Multiply Blending Mode" icon="" text="Select Multiply Blending Mode" whatsThis="" toolTip="Select Multiply Blending Mode" iconText="Select Multiply Blending Mode" shortcut="Alt+Shift+M" defaultShortcut="Alt+Shift+M" isCheckable="false" statusTip=""/>
    <Action name="Select Color Burn Blending Mode" icon="" text="Select Color Burn Blending Mode" whatsThis="" toolTip="Select Color Burn Blending Mode" iconText="Select Color Burn Blending Mode" shortcut="Alt+Shift+B" defaultShortcut="Alt+Shift+B" isCheckable="false" statusTip=""/>
    <Action name="Select Linear Burn Blending Mode" icon="" text="Select Linear Burn Blending Mode" whatsThis="" toolTip="Select Linear Burn Blending Mode" iconText="Select Linear Burn Blending Mode" shortcut="Alt+Shift+A" defaultShortcut="Alt+Shift+A" isCheckable="false" statusTip=""/>
    <Action name="Select Lighten Blending Mode" icon="" text="Select Lighten Blending Mode" whatsThis="" toolTip="Select Lighten Blending Mode" iconText="Select Lighten Blending Mode" shortcut="Alt+Shift+G" defaultShortcut="Alt+Shift+G" isCheckable="false" statusTip=""/>
    <Action name="Select Screen Blending Mode" icon="" text="Select Screen Blending Mode" whatsThis="" toolTip="Select Screen Blending Mode" iconText="Select Screen Blending Mode" shortcut="Alt+Shift+S" defaultShortcut="Alt+Shift+S" isCheckable="false" statusTip=""/>
    <Action name="Select Color Dodge Blending Mode" icon="" text="Select Color Dodge Blending Mode" whatsThis="" toolTip="Select Color Dodge Blending Mode" iconText="Select Color Dodge Blending Mode" shortcut="Alt+Shift+D" defaultShortcut="Alt+Shift+D" isCheckable="false" statusTip=""/>
    <Action name="Select Linear Dodge Blending Mode" icon="" text="Select Linear Dodge Blending Mode" whatsThis="" toolTip="Select Linear Dodge Blending Mode" iconText="Select Linear Dodge Blending Mode" shortcut="Alt+Shift+W" defaultShortcut="Alt+Shift+W" isCheckable="false" statusTip=""/>
    <Action name="Select Overlay Blending Mode" icon="" text="Select Overlay Blending Mode" whatsThis="" toolTip="Select Overlay Blending Mode" iconText="Select Overlay Blending Mode" shortcut="Alt+Shift+O" defaultShortcut="Alt+Shift+O" isCheckable="false" statusTip=""/>
    <Action name="Select Soft Light Blending Mode" icon="" text="Select Soft Light Blending Mode" whatsThis="" toolTip="Select Soft Light Blending Mode" iconText="Select Soft Light Blending Mode" shortcut="Alt+Shift+F" defaultShortcut="Alt+Shift+F" isCheckable="false" statusTip=""/>
    <Action name="Select Hard Light Blending Mode" icon="" text="Select Hard Light Blending Mode" whatsThis="" toolTip="Select Hard Light Blending Mode" iconText="Select Hard Light Blending Mode" shortcut="Alt+Shift+H" defaultShortcut="Alt+Shift+H" isCheckable="false" statusTip=""/>
    <Action name="Select Vivid Light Blending Mode" icon="" text="Select Vivid Light Blending Mode" whatsThis="" toolTip="Select Vivid Light Blending Mode" iconText="Select Vivid Light Blending Mode" shortcut="Alt+Shift+V" defaultShortcut="Alt+Shift+V" isCheckable="false" statusTip=""/>
    <Action name="Select Linear Light Blending Mode" icon="" text="Select Linear Light Blending Mode" whatsThis="" toolTip="Select Linear Light Blending Mode" iconText="Select Linear Light Blending Mode" shortcut="Alt+Shift+J" defaultShortcut="Alt+Shift+J" isCheckable="false" statusTip=""/>
    <Action name="Select Pin Light Blending Mode" icon="" text="Select Pin Light Blending Mode" whatsThis="" toolTip="Select Pin Light Blending Mode" iconText="Select Pin Light Blending Mode" shortcut="Alt+Shift+Z" defaultShortcut="Alt+Shift+Z" isCheckable="false" statusTip=""/>
    <Action name="Select Hard Mix Blending Mode" icon="" text="Select Hard Mix Blending Mode" whatsThis="" toolTip="Select Hard Mix Blending Mode" iconText="Select Hard Mix Blending Mode" shortcut="Alt+Shift+L" defaultShortcut="Alt+Shift+L" isCheckable="false" statusTip=""/>
    <Action name="Select Difference Blending Mode" icon="" text="Select Difference Blending Mode" whatsThis="" toolTip="Select Difference Blending Mode" iconText="Select Difference Blending Mode" shortcut="Alt+Shift+E" defaultShortcut="Alt+Shift+E" isCheckable="false" statusTip=""/>
    <Action name="Select Exclusion Blending Mode" icon="" text="Select Exclusion Blending Mode" whatsThis="" toolTip="Select Exclusion Blending Mode" iconText="Select Exclusion Blending Mode" shortcut="Alt+Shift+X" defaultShortcut="Alt+Shift+X" isCheckable="false" statusTip=""/>
    <Action name="Select Hue Blending Mode" icon="" text="Select Hue Blending Mode" whatsThis="" toolTip="Select Hue Blending Mode" iconText="Select Hue Blending Mode" shortcut="Alt+Shift+U" defaultShortcut="Alt+Shift+U" isCheckable="false" statusTip=""/>
    <Action name="Select Saturation Blending Mode" icon="" text="Select Saturation Blending Mode" whatsThis="" toolTip="Select Saturation Blending Mode" iconText="Select Saturation Blending Mode" shortcut="Alt+Shift+T" defaultShortcut="Alt+Shift+T" isCheckable="false" statusTip=""/>
    <Action name="Select Color Blending Mode" icon="" text="Select Color Blending Mode" whatsThis="" toolTip="Select Color Blending Mode" iconText="Select Color Blending Mode" shortcut="Alt+Shift+C" defaultShortcut="Alt+Shift+C" isCheckable="false" statusTip=""/>
    <Action name="Select Luminosity Blending Mode" icon="" text="Select Luminosity Blending Mode" whatsThis="" toolTip="Select Luminosity Blending Mode" iconText="Select Luminosity Blending Mode" shortcut="Alt+Shift+Y" defaultShortcut="Alt+Shift+Y" isCheckable="false" statusTip=""/>
    <Action name="composite_actions" icon="" text="Brush composite" whatsThis="" toolTip="Brush composite" iconText="Brush composite" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="brushslider1" icon="" text="Brush option slider 1" whatsThis="" toolTip="Brush option slider 1" iconText="Brush option slider 1" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="brushslider2" icon="" text="Brush option slider 2" whatsThis="" toolTip="Brush option slider 2" iconText="Brush option slider 2" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="brushslider3" icon="" text="Brush option slider 3" whatsThis="" toolTip="Brush option slider 3" iconText="Brush option slider 3" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="next_favorite_preset" icon="" text="Next Favourite Preset" whatsThis="" toolTip="Next Favourite Preset" iconText="Next Favourite Preset" shortcut="," defaultShortcut="," isCheckable="false" statusTip=""/>
    <Action name="previous_favorite_preset" icon="" text="Previous Favourite Preset" whatsThis="" toolTip="Previous Favourite Preset" iconText="Previous Favourite Preset" shortcut="." defaultShortcut="." isCheckable="false" statusTip=""/>
    <Action name="previous_preset" icon="" text="Switch to Previous Preset" whatsThis="" toolTip="Switch to Previous Preset" iconText="Switch to Previous Preset" shortcut="/" defaultShortcut="/" isCheckable="false" statusTip=""/>
    <Action name="mirror_actions" icon="" text="Mirror" whatsThis="" toolTip="Mirror" iconText="Mirror" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="workspaces" icon="" text="Workspaces" whatsThis="" toolTip="Workspaces" iconText="Workspaces" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="paintops" icon="" text="&amp;Painter's Tools" whatsThis="" toolTip="Painter's Tools" iconText="Painter's Tools" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_new" icon="light_document-new" text="&amp;New" whatsThis="" toolTip="Create new document" iconText="New" shortcut="Ctrl+N" defaultShortcut="Ctrl+N" isCheckable="false" statusTip=""/>
    <Action name="file_open" icon="document-open" text="&amp;Open..." whatsThis="" toolTip="Open an existing document" iconText="Open" shortcut="Ctrl+O" defaultShortcut="Ctrl+O" isCheckable="false" statusTip=""/>
    <Action name="file_open_recent" icon="document-open-recent" text="Open &amp;Recent" whatsThis="" toolTip="Open a document which was recently opened" iconText="Open Recent" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_save" icon="document-save" text="&amp;Save" whatsThis="" toolTip="Save" iconText="Save" shortcut="Ctrl+S" defaultShortcut="Ctrl+S" isCheckable="false" statusTip=""/>
    <Action name="file_save_as" icon="document-save-as" text="Save &amp;As..." whatsThis="" toolTip="Save document under a new name" iconText="Save As" shortcut="Ctrl+Shift+S" defaultShortcut="Ctrl+Shift+S" isCheckable="false" statusTip=""/>
    <Action name="file_print" icon="document-print" text="&amp;Print..." whatsThis="" toolTip="Print document" iconText="Print" shortcut="Ctrl+P" defaultShortcut="Ctrl+P" isCheckable="false" statusTip=""/>
    <Action name="file_print_preview" icon="document-print-preview" text="Print Previe&amp;w" whatsThis="" toolTip="Show a print preview of document" iconText="Print Preview" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="edit_undo" icon="light_edit-undo" text="Undo" whatsThis="" toolTip="Undo last action" iconText="Undo" shortcut="Ctrl+Z" defaultShortcut="Ctrl+Z" isCheckable="false" statusTip=""/>
    <Action name="edit_redo" icon="light_edit-redo" text="Redo" whatsThis="" toolTip="Redo last undone action" iconText="Redo" shortcut="Ctrl+Shift+Z" defaultShortcut="Ctrl+Shift+Z" isCheckable="false" statusTip=""/>
    <Action name="file_export_pdf" icon="application-pdf" text="Export as PDF..." whatsThis="" toolTip="Export as PDF" iconText="Export as PDF" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_quit" icon="application-exit" text="&amp;Quit" whatsThis="" toolTip="Quit application" iconText="Quit" shortcut="Ctrl+Q" defaultShortcut="Ctrl+Q" isCheckable="false" statusTip=""/>
    <Action name="file_close_all" icon="" text="Close All" whatsThis="" toolTip="Close All" iconText="Close All" shortcut="Ctrl+Shift+W" defaultShortcut="Ctrl+Shift+W" isCheckable="false" statusTip=""/>
    <Action name="file_reload_file" icon="" text="Reload" whatsThis="" toolTip="Reload" iconText="Reload" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_import_file" icon="document-import" text="Open ex&amp;isting Document as Untitled Document..." whatsThis="" toolTip="Open existing Document as Untitled Document" iconText="Open existing Document as Untitled Document" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_export_file" icon="document-export" text="E&amp;xport..." whatsThis="" toolTip="Export" iconText="Export" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_documentinfo" icon="document-properties" text="Document Information" whatsThis="" toolTip="Document Information" iconText="Document Information" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="options_configure_keybinding" icon="configure-shortcuts" text="Configure S&amp;hortcuts..." whatsThis="" toolTip="Configure Shortcuts" iconText="Configure Shortcuts" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="options_configure_toolbars" icon="light_configure" text="Configure Tool&amp;bars..." whatsThis="" toolTip="Configure Toolbars" iconText="Configure Toolbars" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="theme_menu" icon="" text="&amp;Themes" whatsThis="" toolTip="Themes" iconText="Themes" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="fullscreen" icon="view-fullscreen" text="F&amp;ull Screen Mode" whatsThis="" toolTip="Display the window in full screen" iconText="Full Screen Mode" shortcut="Ctrl+Shift+F" defaultShortcut="Ctrl+Shift+F" isCheckable="false" statusTip=""/>
    <Action name="view_toggledockers" icon="" text="Show Dockers" whatsThis="" toolTip="Show Dockers" iconText="Show Dockers" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="view_toggledockertitlebars" icon="" text="Show Docker Titlebars" whatsThis="" toolTip="Show Docker Titlebars" iconText="Show Docker Titlebars" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="settings_dockers_menu" icon="" text="Dockers" whatsThis="" toolTip="Dockers" iconText="Dockers" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="window" icon="" text="&amp;Window" whatsThis="" toolTip="Window" iconText="Window" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="windows_cascade" icon="" text="Cascade" whatsThis="" toolTip="Cascade" iconText="Cascade" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="windows_tile" icon="" text="Tile" whatsThis="" toolTip="Tile" iconText="Tile" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="windows_next" icon="" text="Next" whatsThis="" toolTip="Next" iconText="Next" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="windows_previous" icon="" text="Previous" whatsThis="" toolTip="Previous" iconText="Previous" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="view_newwindow" icon="light_window-new" text="&amp;New Window" whatsThis="" toolTip="New Window" iconText="New Window" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="file_close" icon="" text="Close" whatsThis="" toolTip="Close" iconText="Close" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="options_configure" icon="configure" text="&amp;Configure Krita..." whatsThis="" toolTip="Configure Krita" iconText="Configure Krita" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="clones_array" icon="" text="Clones &amp;Array..." whatsThis="" toolTip="Clones Array" iconText="Clones Array" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="colorrange" icon="" text="Select from Color Range..." whatsThis="" toolTip="Select from Color Range" iconText="Select from Color Range" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="selectopaque" icon="" text="Select Opaque" whatsThis="" toolTip="Select Opaque" iconText="Select Opaque" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="imagecolorspaceconversion" icon="" text="&amp;Convert Image Color Space..." whatsThis="" toolTip="Convert Image Color Space" iconText="Convert Image Color Space" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="layercolorspaceconversion" icon="" text="&amp;Convert Layer Color Space..." whatsThis="" toolTip="Convert Layer Color Space" iconText="Convert Layer Color Space" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="gmic" icon="" text="Apply G'Mic Action..." whatsThis="" toolTip="Apply G'Mic Action" iconText="Apply G'Mic Action" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="histogram" icon="" text="&amp;Histogram..." whatsThis="" toolTip="Histogram" iconText="Histogram" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="imagesize" icon="" text="Scale To New Size..." whatsThis="" toolTip="Scale To New Size" iconText="Scale To New Size" shortcut="Ctrl+Alt+I" defaultShortcut="Ctrl+Alt+I" isCheckable="false" statusTip=""/>
    <Action name="canvassize" icon="" text="Size Canvas..." whatsThis="" toolTip="Size Canvas" iconText="Size Canvas" shortcut="Ctrl+Alt+C" defaultShortcut="Ctrl+Alt+C" isCheckable="false" statusTip=""/>
    <Action name="layersize" icon="" text="Scale &amp;Layer..." whatsThis="" toolTip="Scale Layer" iconText="Scale Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="selectionscale" icon="" text="&amp;Scale..." whatsThis="" toolTip="Scale" iconText="Scale" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="imagesplit" icon="" text="Image Split " whatsThis="" toolTip="Image Split" iconText="Image Split" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="layersplit" icon="" text="Split Layer..." whatsThis="" toolTip="Split Layer" iconText="Split Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="growselection" icon="" text="Grow Selection..." whatsThis="" toolTip="Grow Selection" iconText="Grow Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="shrinkselection" icon="" text="Shrink Selection..." whatsThis="" toolTip="Shrink Selection" iconText="Shrink Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="borderselection" icon="" text="Border Selection..." whatsThis="" toolTip="Border Selection" iconText="Border Selection" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="featherselection" icon="" text="Feather Selection..." whatsThis="" toolTip="Feather Selection" iconText="Feather Selection" shortcut="Shift+F6" defaultShortcut="Shift+F6" isCheckable="false" statusTip=""/>
    <Action name="smoothselection" icon="" text="Smooth" whatsThis="" toolTip="Smooth" iconText="Smooth" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="offsetimage" icon="" text="&amp;Offset Image..." whatsThis="" toolTip="Offset Image" iconText="Offset Image" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="offsetlayer" icon="" text="&amp;Offset Layer..." whatsThis="" toolTip="Offset Layer" iconText="Offset Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="LayerGroupSwitcher/previous" icon="" text="Move into previous group" whatsThis="" toolTip="Move into previous group" iconText="Move into previous group" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="LayerGroupSwitcher/next" icon="" text="Move into next group" whatsThis="" toolTip="Move into next group" iconText="Move into next group" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="import_resources" icon="" text="Import Resources or Bundles..." whatsThis="" toolTip="Import Resources or Bundles" iconText="Import Resources or Bundles" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="create_bundle" icon="" text="Create Resource Bundle..." whatsThis="" toolTip="Create Resource Bundle" iconText="Create Resource Bundle" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="manage_bundles" icon="" text="Manage Resource Bundles..." whatsThis="" toolTip="Manage Resource Bundles" iconText="Manage Resource Bundles" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateimage" icon="" text="&amp;Rotate Image..." whatsThis="" toolTip="Rotate Image" iconText="Rotate Image" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateImageCW90" icon="object-rotate-right" text="Rotate Image 90&#xB0; to the Right" whatsThis="" toolTip="Rotate Image 90&#xB0; to the Right" iconText="Rotate Image 90&#xB0; to the Right" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateImage180" icon="" text="Rotate Image 180&#xB0;" whatsThis="" toolTip="Rotate Image 180&#xB0;" iconText="Rotate Image 180&#xB0;" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateImageCCW90" icon="object-rotate-left" text="Rotate Image 90&#xB0; to the Left" whatsThis="" toolTip="Rotate Image 90&#xB0; to the Left" iconText="Rotate Image 90&#xB0; to the Left" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="mirrorImageHorizontal" icon="light_symmetry-horizontal" text="Mirror Image Horizontally" whatsThis="" toolTip="Mirror Image Horizontally" iconText="Mirror Image Horizontally" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="mirrorImageVertical" icon="light_symmetry-vertical" text="Mirror Image Vertically" whatsThis="" toolTip="Mirror Image Vertically" iconText="Mirror Image Vertically" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotatelayer" icon="" text="&amp;Rotate Layer..." whatsThis="" toolTip="Rotate Layer" iconText="Rotate Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateLayer180" icon="" text="Rotate Layer 180&#xB0;" whatsThis="" toolTip="Rotate Layer 180&#xB0;" iconText="Rotate Layer 180&#xB0;" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateLayerCW90" icon="object-rotate-right" text="Rotate Layer 90&#xB0; to the Right" whatsThis="" toolTip="Rotate Layer 90&#xB0; to the Right" iconText="Rotate Layer 90&#xB0; to the Right" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="rotateLayerCCW90" icon="object-rotate-left" text="Rotate Layer 90&#xB0; to the Left" whatsThis="" toolTip="Rotate Layer 90&#xB0; to the Left" iconText="Rotate Layer 90&#xB0; to the Left" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="separate" icon="" text="Separate Image..." whatsThis="" toolTip="Separate Image" iconText="Separate Image" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="shearimage" icon="" text="&amp;Shear Image..." whatsThis="" toolTip="Shear Image" iconText="Shear Image" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="shearlayer" icon="" text="&amp;Shear Layer..." whatsThis="" toolTip="Shear Layer" iconText="Shear Layer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="Macro_Open_Play" icon="media-playback-start" text="Open and play..." whatsThis="" toolTip="Open and play" iconText="Open and play" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="Macro_Open_Edit" icon="document-edit" text="Open and edit..." whatsThis="" toolTip="Open and edit" iconText="Open and edit" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="Recording_Start_Recording_Macro" icon="media-record" text="Start recording macro" whatsThis="" toolTip="Start recording macro" iconText="Start recording macro" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="Recording_Stop_Recording_Macro" icon="media-playback-stop" text="Stop recording actions" whatsThis="" toolTip="Stop recording actions" iconText="Stop recording actions" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="EditLayerMetaData" icon="" text="&amp;Edit metadata..." whatsThis="" toolTip="Edit metadata" iconText="Edit metadata" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="help_contents" icon="help-contents" text="Krita &amp;Handbook" whatsThis="" toolTip="Krita Handbook" iconText="Krita Handbook" shortcut="F1" defaultShortcut="F1" isCheckable="false" statusTip=""/>
    <Action name="help_report_bug" icon="tools-report-bug" text="&amp;Report Bug..." whatsThis="" toolTip="Report Bug" iconText="Report Bug" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="switch_application_language" icon="preferences-desktop-locale" text="Switch Application &amp;Language..." whatsThis="" toolTip="Switch Application Language" iconText="Switch Application Language" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="help_about_app" icon="calligrakrita" text="&amp;About Krita" whatsThis="" toolTip="About Krita" iconText="About Krita" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="help_about_kde" icon="kde" text="About &amp;KDE" whatsThis="" toolTip="About KDE" iconText="About KDE" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="mainToolBar" icon="" text="Show File Toolbar" whatsThis="" toolTip="Show File Toolbar" iconText="Show File Toolbar" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="BrushesAndStuff" icon="" text="Hide Brushes and Stuff Toolbar" whatsThis="" toolTip="Hide Brushes and Stuff Toolbar" iconText="Hide Brushes and Stuff Toolbar" shortcut="" defaultShortcut="" isCheckable="true" statusTip=""/>
    <Action name="zoom_in" icon="zoom-in" text="Zoom &amp;In" whatsThis="" toolTip="Zoom In" iconText="Zoom In" shortcut="Ctrl++; Ctrl+=" defaultShortcut="Ctrl++; Ctrl+=" isCheckable="false" statusTip=""/>
    <Action name="zoom_out" icon="zoom-out" text="Zoom &amp;Out" whatsThis="" toolTip="Zoom Out" iconText="Zoom Out" shortcut="Ctrl+-" defaultShortcut="Ctrl+-" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolDyna" icon="" text="Dynamic Brush Tool" whatsThis="" toolTip="Dynamic Brush Tool" iconText="Dynamic Brush Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolCrop" icon="" text="Crop the image to an area" whatsThis="" toolTip="Crop the image to an area" iconText="Crop the image to an area" shortcut="C" defaultShortcut="C" isCheckable="false" statusTip=""/>
    <Action name="KisToolPerspectiveGrid" icon="" text="Edit the perspective grid" whatsThis="" toolTip="Edit the perspective grid" iconText="Edit the perspective grid" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolPolygon" icon="" text="Polygon Tool. Shift-mouseclick ends the polygon." whatsThis="" toolTip="Polygon Tool. Shift-mouseclick ends the polygon." iconText="Polygon Tool. Shift-mouseclick ends the polygon." shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="ReferencesToolFactory_ID" icon="" text="References" whatsThis="" toolTip="References" iconText="References" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolRectangle" icon="" text="Rectangle Tool" whatsThis="" toolTip="Rectangle Tool" iconText="Rectangle Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolMultiBrush" icon="" text="Multibrush Tool" whatsThis="" toolTip="Multibrush Tool" iconText="Multibrush Tool" shortcut="Q" defaultShortcut="Q" isCheckable="false" statusTip=""/>
    <Action name="InteractionTool" icon="" text="Shape handling" whatsThis="" toolTip="Shape handling" iconText="Shape handling" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaSelected/KisToolColorPicker" icon="" text="Select a color from the image or current layer" whatsThis="" toolTip="Select a color from the image or current layer" iconText="Select a color from the image or current layer" shortcut="P" defaultShortcut="P" isCheckable="false" statusTip=""/>
    <Action name="TextToolFactory_ID" icon="" text="Text editing" whatsThis="" toolTip="Text editing" iconText="Text editing" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectOutline" icon="" text="Outline Selection Tool" whatsThis="" toolTip="Outline Selection Tool" iconText="Outline Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="ArtisticTextToolFactoryID" icon="" text="Artistic text editing" whatsThis="" toolTip="Artistic text editing" iconText="Artistic text editing" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectPath" icon="" text="Bezier Curve Selection Tool" whatsThis="" toolTip="Bezier Curve Selection Tool" iconText="Bezier Curve Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectSimilar" icon="" text="Similar Color Selection Tool" whatsThis="" toolTip="Similar Color Selection Tool" iconText="Similar Color Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaFill/KisToolFill" icon="" text="Fill a contiguous area of color with a color, or fill a selection." whatsThis="" toolTip="Fill a contiguous area of color with a color, or fill a selection." iconText="Fill a contiguous area of color with a color, or fill a selection." shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolLine" icon="" text="Line Tool" whatsThis="" toolTip="Line Tool" iconText="Line Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolPencil" icon="" text="Freehand Path Tool" whatsThis="" toolTip="Freehand Path Tool" iconText="Freehand Path Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolPath" icon="" text="Bezier Curve Tool. Shift-mouseclick ends the curve." whatsThis="" toolTip="Bezier Curve Tool. Shift-mouseclick ends the curve." iconText="Bezier Curve Tool. Shift-mouseclick ends the curve." shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolEllipse" icon="" text="Ellipse Tool" whatsThis="" toolTip="Ellipse Tool" iconText="Ellipse Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolBrush" icon="" text="Freehand Brush Tool" whatsThis="" toolTip="Freehand Brush Tool" iconText="Freehand Brush Tool" shortcut="B" defaultShortcut="B" isCheckable="false" statusTip=""/>
    <Action name="CreateShapesTool" icon="" text="Create object" whatsThis="" toolTip="Create object" iconText="Create object" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectElliptical" icon="" text="Elliptical Selection Tool" whatsThis="" toolTip="Elliptical Selection Tool" iconText="Elliptical Selection Tool" shortcut="J" defaultShortcut="J" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectContiguous" icon="" text="Contiguous Selection Tool" whatsThis="" toolTip="Contiguous Selection Tool" iconText="Contiguous Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KarbonPatternTool" icon="" text="Pattern editing" whatsThis="" toolTip="Pattern editing" iconText="Pattern editing" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="ReviewToolFactory_ID" icon="" text="Review" whatsThis="" toolTip="Review" iconText="Review" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaFill/KisToolGradient" icon="" text="Draw a gradient." whatsThis="" toolTip="Draw a gradient." iconText="Draw a gradient." shortcut="G" defaultShortcut="G" isCheckable="false" statusTip=""/>
    <Action name="KisToolGrid" icon="" text="Edit the grid" whatsThis="" toolTip="Edit the grid" iconText="Edit the grid" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectPolygonal" icon="" text="Polygonal Selection Tool" whatsThis="" toolTip="Polygonal Selection Tool" iconText="Polygonal Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolMeasure" icon="" text="Measure the distance between two points" whatsThis="" toolTip="Measure the distance between two points" iconText="Measure the distance between two points" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectRectangular" icon="" text="Rectangular Selection Tool" whatsThis="" toolTip="Rectangular Selection Tool" iconText="Rectangular Selection Tool" shortcut="Ctrl+R" defaultShortcut="Ctrl+R" isCheckable="false" statusTip=""/>
    <Action name="KritaTransform/KisToolMove" icon="" text="Move a layer" whatsThis="" toolTip="Move a layer" iconText="Move a layer" shortcut="T" defaultShortcut="T" isCheckable="false" statusTip=""/>
    <Action name="VectorToolFactoryId" icon="" text="Vector Image (EMF/WMF/SVM/SVG) tool" whatsThis="" toolTip="Vector Image (EMF/WMF/SVM/SVG) tool" iconText="Vector Image (EMF/WMF/SVM/SVG) tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KarbonCalligraphyTool" icon="" text="Calligraphy" whatsThis="" toolTip="Calligraphy" iconText="Calligraphy" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="PathToolFactoryId" icon="" text="Path editing" whatsThis="" toolTip="Path editing" iconText="Path editing" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolPolyline" icon="" text="Polyline Tool. Shift-mouseclick ends the polyline." whatsThis="" toolTip="Polyline Tool. Shift-mouseclick ends the polyline." iconText="Polyline Tool. Shift-mouseclick ends the polyline." shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolTransform" icon="" text="Transform a layer or a selection" whatsThis="" toolTip="Transform a layer or a selection" iconText="Transform a layer or a selection" shortcut="Ctrl+T" defaultShortcut="Ctrl+T" isCheckable="false" statusTip=""/>
    <Action name="KisRulerAssistantTool" icon="" text="Ruler assistant editor tool" whatsThis="" toolTip="Ruler assistant editor tool" iconText="Ruler assistant editor tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KritaShape/KisToolText" icon="" text="Text tool" whatsThis="" toolTip="Text tool" iconText="Text tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KarbonGradientTool" icon="" text="Gradient editing" whatsThis="" toolTip="Gradient editing" iconText="Gradient editing" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="KisToolSelectBrush" icon="" text="Brush Selection Tool" whatsThis="" toolTip="Brush Selection Tool" iconText="Brush Selection Tool" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="reset_fg_bg" icon="" text="Reset Foreground and Background Color" whatsThis="" toolTip="Reset Foreground and Background Color" iconText="Reset Foreground and Background Color" shortcut="D" defaultShortcut="D" isCheckable="false" statusTip=""/>
    <Action name="toggle_fg_bg" icon="" text="Swap Foreground and Background Color" whatsThis="" toolTip="Swap Foreground and Background Color" iconText="Swap Foreground and Background Color" shortcut="X" defaultShortcut="X" isCheckable="false" statusTip=""/>
    <Action name="set_weighted_brush_smoothing" icon="" text="Brush Smoothing: Weighted" whatsThis="" toolTip="Brush Smoothing: Weighted" iconText="Brush Smoothing: Weighted" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="set_no_brush_smoothing" icon="" text="Brush Smoothing: Disabled" whatsThis="" toolTip="Brush Smoothing: Disabled" iconText="Brush Smoothing: Disabled" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="set_stabilizer_brush_smoothing" icon="" text="Brush Smoothing: Stabilizer" whatsThis="" toolTip="Brush Smoothing: Stabilizer" iconText="Brush Smoothing: Stabilizer" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="decrease_brush_size" icon="" text="Decrease Brush Size" whatsThis="" toolTip="Decrease Brush Size" iconText="Decrease Brush Size" shortcut="[" defaultShortcut="[" isCheckable="false" statusTip=""/>
    <Action name="set_simple_brush_smoothing" icon="" text="Brush Smoothing: Basic" whatsThis="" toolTip="Brush Smoothing: Basic" iconText="Brush Smoothing: Basic" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="increase_brush_size" icon="" text="Increase Brush Size" whatsThis="" toolTip="Increase Brush Size" iconText="Increase Brush Size" shortcut="]" defaultShortcut="]" isCheckable="false" statusTip=""/>
    <Action name="show_color_selector" icon="" text="Show color selector" whatsThis="" toolTip="Show color selector" iconText="Show color selector" shortcut="Shift+I" defaultShortcut="Shift+I" isCheckable="false" statusTip=""/>
    <Action name="show_mypaint_shade_selector" icon="" text="Show MyPaint shade selector" whatsThis="" toolTip="Show MyPaint shade selector" iconText="Show MyPaint shade selector" shortcut="Shift+M" defaultShortcut="Shift+M" isCheckable="false" statusTip=""/>
    <Action name="show_minimal_shade_selector" icon="" text="Show minimal shade selector" whatsThis="" toolTip="Show minimal shade selector" iconText="Show minimal shade selector" shortcut="Shift+N" defaultShortcut="Shift+N" isCheckable="false" statusTip=""/>
    <Action name="show_color_history" icon="" text="Show color history" whatsThis="" toolTip="Show color history" iconText="Show color history" shortcut="H" defaultShortcut="H" isCheckable="false" statusTip=""/>
    <Action name="show_common_colors" icon="" text="Show common colors" whatsThis="" toolTip="Show common colors" iconText="Show common colors" shortcut="U" defaultShortcut="U" isCheckable="false" statusTip=""/>
    <Action name="toggle_assistant" icon="" text="Toggle Assistant" whatsThis="" toolTip="Toggle Assistant" iconText="ToggleAssistant" shortcut="Ctrl+Shift+L" defaultShortcut="Ctrl+Shift+L" isCheckable="true" statusTip=""/>
    <Action name="undo_polygon_selection" icon="" text="Undo Polygon Selection Points" whatsThis="" toolTip="Undo Polygon Selection Points" iconText="Undo Polygon Selection Points" shortcut="Shift+Z" defaultShortcut="Shift+Z" isCheckable="false" statusTip=""/>
    <Action name="" icon="show_tool_options" text="Show Tool Options" whatsThis="" toolTip="Show Tool Options" iconText="Show Tool Options" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="" icon="show_tool_options" text="Show Brush Editor" whatsThis="" toolTip="Show Brush Editor" iconText="Show Brush Editor" shortcut="i" defaultShortcut="" isCheckable="false" statusTip=""/>
    <Action name="" icon="show_tool_options" text="Show Brush Presets" whatsThis="" toolTip="Show Brush Presets" iconText="Show Brush Presets" shortcut="" defaultShortcut="" isCheckable="false" statusTip=""/>
</Actions>
