<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Menu">
  <Actions category="File">
    <text>File</text>
    <Action name="file_new">
      <icon>document-new</icon>
      <text context="New document">&amp;New...</text>
      <whatsThis></whatsThis>
      <toolTip>Create new document</toolTip>
      <iconText>New</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+N</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_open">
      <icon>document-open</icon>
      <text>&amp;Open...</text>
      <whatsThis></whatsThis>
      <toolTip>Open an existing document</toolTip>
      <iconText>Open</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+O</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_open_recent">
      <icon>document-open-recent</icon>
      <text>Open &amp;Recent</text>
      <whatsThis></whatsThis>
      <toolTip>Open a document which was recently opened</toolTip>
      <iconText>Open Recent</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_save">
      <icon>document-save</icon>
      <text>&amp;Save</text>
      <whatsThis></whatsThis>
      <toolTip>Save</toolTip>
      <iconText>Save</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+S</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_save_as">
      <icon>document-save-as</icon>
      <text>Save &amp;As...</text>
      <whatsThis></whatsThis>
      <toolTip>Save document under a new name</toolTip>
      <iconText>Save As</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+S</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_sessions">
      <icon></icon>
      <text>Sessions...</text>
      <whatsThis></whatsThis>
      <toolTip>Open session manager</toolTip>
      <iconText>Sessions</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="file_import_file">
      <icon>document-import</icon>
      <text>Open ex&amp;isting Document as Untitled Document...</text>
      <whatsThis></whatsThis>
      <toolTip>Open existing Document as Untitled Document</toolTip>
      <iconText>Open existing Document as Untitled Document</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_export_file">
      <icon>document-export</icon>
      <text>E&amp;xport...</text>
      <whatsThis></whatsThis>
      <toolTip>Export</toolTip>
      <iconText>Export</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_export_advanced">
      <icon>document-export</icon>
      <text>Export Advanced...</text>
      <whatsThis></whatsThis>
      <toolTip>Advanced Export</toolTip>
      <iconText>Export</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="file_import_animation">
      <icon></icon>
      <text>Import animation frames...</text>
      <whatsThis></whatsThis>
      <toolTip>Import animation frames</toolTip>
      <iconText>Import animation frames</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_import_video_animation">
      <icon></icon>
      <text>Import video animation...</text>
      <whatsThis></whatsThis>
      <toolTip>Import video animation</toolTip>
      <iconText>Import video animation</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="render_animation">
      <icon></icon>
      <text>&amp;Render Animation...</text>
      <whatsThis></whatsThis>
      <toolTip>Render Animation to GIF, Image Sequence or Video</toolTip>
      <iconText>Render Animation</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
      <Action name="render_animation_again">
      <icon></icon>
      <text>&amp;Render Animation Again</text>
      <whatsThis></whatsThis>
      <toolTip>Render Animation Again</toolTip>
      <iconText>Render Animation</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>    
    <Action name="save_incremental_version">
      <icon></icon>
      <text>Save Incremental &amp;Version</text>
      <whatsThis></whatsThis>
      <toolTip>Save Incremental Version</toolTip>
      <iconText>Save Incremental Version</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Alt+S</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="save_incremental_backup">
      <icon></icon>
      <text>Save Incremental &amp;Backup</text>
      <whatsThis></whatsThis>
      <toolTip>Save Incremental Backup</toolTip>
      <iconText>Save Incremental Backup</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>F4</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="create_template">
      <icon></icon>
      <text>&amp;Create Template From Image...</text>
      <whatsThis></whatsThis>
      <toolTip>Create Template From Image</toolTip>
      <iconText>Create Template From Image</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="create_copy">
      <icon></icon>
      <text>Create Copy &amp;From Current Image</text>
      <whatsThis></whatsThis>
      <toolTip>Create Copy From Current Image</toolTip>
      <iconText>Create Copy From Current Image</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_documentinfo">
      <icon>configure</icon>
      <text>&amp;Document Information</text>
      <whatsThis></whatsThis>
      <toolTip>Document Information</toolTip>
      <iconText>Document Information</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_close_all">
      <icon></icon>
      <text>&amp;Close All</text>
      <whatsThis></whatsThis>
      <toolTip>Close All</toolTip>
      <iconText>Close All</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+W</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_close">
      <icon></icon>
      <text>C&amp;lose</text>
      <whatsThis></whatsThis>
      <toolTip>Close</toolTip>
      <iconText>Close</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+W</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="file_quit">
      <icon></icon>
      <text>&amp;Quit</text>
      <whatsThis></whatsThis>
      <toolTip>Quit application</toolTip>
      <iconText>Quit</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Q</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="Edit">
    <text>Edit</text>
    <Action name="edit_undo">
      <icon>edit-undo</icon>
      <text>Undo</text>
      <whatsThis></whatsThis>
      <toolTip>Undo last action</toolTip>
      <iconText>Undo</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Z</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edit_redo">
      <icon>edit-redo</icon>
      <text>Redo</text>
      <whatsThis></whatsThis>
      <toolTip>Redo last undone action</toolTip>
      <iconText>Redo</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+Z</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edit_cut">
      <icon>edit-cut</icon>
      <text>Cu&amp;t</text>
      <whatsThis></whatsThis>
      <toolTip>Cut selection to clipboard</toolTip>
      <iconText>Cut</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+X</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edit_copy">
      <icon>edit-copy</icon>
      <text>&amp;Copy</text>
      <whatsThis></whatsThis>
      <toolTip>Copy selection to clipboard</toolTip>
      <iconText>Copy</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+C</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="copy_sharp">
      <icon></icon>
      <text>C&amp;opy (sharp)</text>
      <whatsThis></whatsThis>
      <toolTip>Copy (sharp)</toolTip>
      <iconText>Copy (sharp)</iconText>
      <activationFlags>100000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="cut_sharp">
      <icon></icon>
      <text>Cut (&amp;sharp)</text>
      <whatsThis></whatsThis>
      <toolTip>Cut (sharp)</toolTip>
      <iconText>Cut (sharp)</iconText>
      <activationFlags>100000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="copy_merged">
      <icon></icon>
      <text>Copy &amp;merged</text>
      <whatsThis></whatsThis>
      <toolTip>Copy merged</toolTip>
      <iconText>Copy merged</iconText>
      <activationFlags>100000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+C</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="copy_layer_style">
      <icon></icon>
      <text>Copy Layer Style</text>
      <whatsThis></whatsThis>
      <toolTip>Copy Layer Style from the Current Node</toolTip>
      <iconText>Copy Layer Style</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edit_paste">
      <icon>edit-paste</icon>
      <text>&amp;Paste</text>
      <whatsThis></whatsThis>
      <toolTip>Paste clipboard content</toolTip>
      <iconText>Paste</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+V</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_at">
      <icon></icon>
      <text>Paste at Cursor</text>
      <whatsThis></whatsThis>
      <toolTip>Paste at cursor</toolTip>
      <iconText>Paste at cursor</iconText>
      <activationFlags>1100000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Alt+V</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_into">
      <icon></icon>
      <text>Paste into Active Layer</text>
      <whatsThis></whatsThis>
      <toolTip>Paste into Active Layer</toolTip>
      <iconText>Paste into Active Layer</iconText>
      <activationFlags>100000000000</activationFlags>
      <activationConditions>10</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_new">
      <icon></icon>
      <text>Paste into &amp;New Image</text>
      <whatsThis></whatsThis>
      <toolTip>Paste into New Image</toolTip>
      <iconText>Paste into New Image</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+N</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_shape_style">
      <icon></icon>
      <text>Paste Shape Style</text>
      <whatsThis></whatsThis>
      <toolTip>Paste Shape Style</toolTip>
      <iconText>Paste into New Image</iconText>
      <activationFlags>1000000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_as_reference">
      <icon></icon>
      <text>Paste as R&amp;eference Image</text>
      <whatsThis></whatsThis>
      <toolTip>Paste as Reference Image</toolTip>
      <iconText>Paste as Reference Image</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+R</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="paste_layer_style">
      <icon></icon>
      <text>Paste Layer Style</text>
      <whatsThis></whatsThis>
      <toolTip>Paste Layer Style into the Current Node</toolTip>
      <iconText>Paste Layer Style</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="clear">
      <icon>edit-clear</icon>
      <text>C&amp;lear</text>
      <whatsThis></whatsThis>
      <toolTip>Clear</toolTip>
      <iconText>Clear</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut operatingSystem="macos">Backspace</shortcut>
      <shortcut operatingSystemElse="">Del</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="fill_selection_foreground_color">
      <icon></icon>
      <text>&amp;Fill with Foreground Color</text>
      <whatsThis></whatsThis>
      <toolTip>Fill with Foreground Color</toolTip>
      <iconText>Fill with Foreground Color</iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>1</activationConditions>
      <shortcut>Shift+Backspace</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="fill_selection_background_color">
      <icon></icon>
      <text>Fill &amp;with Background Color</text>
      <whatsThis></whatsThis>
      <toolTip>Fill with Background Color</toolTip>
      <iconText>Fill with Background Color</iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>1</activationConditions>
      <shortcut operatingSystem="macos">Del</shortcut>
      <shortcut operatingSystemElse="">Backspace</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="fill_selection_pattern">
      <icon></icon>
      <text>F&amp;ill with Pattern</text>
      <whatsThis></whatsThis>
      <toolTip>Fill with Pattern</toolTip>
      <iconText>Fill with Pattern</iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>1</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Actions category="EditFill">
      <text>Fill Special</text>
       <Action name="fill_selection_foreground_color_opacity">
        <icon></icon>
        <text>Fill with Foreground Color (Opacity)</text>
        <whatsThis></whatsThis>
        <toolTip>Fill with Foreground Color (Opacity)</toolTip>
        <iconText>Fill with Foreground Color (Opacity)</iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>1</activationConditions>
        <shortcut>Ctrl+Shift+Backspace</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
      </Action>
      <Action name="fill_selection_background_color_opacity">
        <icon></icon>
        <text>Fill with Background Color (Opacity)</text>
        <whatsThis></whatsThis>
        <toolTip>Fill with Background Color (Opacity)</toolTip>
        <iconText>Fill with Background Color (Opacity)</iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>1</activationConditions>
        <shortcut>Ctrl+Backspace</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
      </Action>
      <Action name="fill_selection_pattern_opacity">
        <icon></icon>
        <text>Fill with Pattern (Opacity)</text>
        <whatsThis></whatsThis>
        <toolTip>Fill with Pattern (Opacity)</toolTip>
        <iconText>Fill with Pattern (Opacity)</iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>1</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
      </Action>
    </Actions>
    <Action name="stroke_shapes">
      <icon></icon>
      <text>Stro&amp;ke selected shapes</text>
      <whatsThis></whatsThis>
      <toolTip>Stroke selected shapes</toolTip>
      <iconText>Stroke selected shapes</iconText>
      <activationFlags>1000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="stroke_selection">
      <icon></icon>
      <text>Stroke Selec&amp;tion...</text>
      <whatsThis></whatsThis>
      <toolTip>Stroke selection</toolTip>
      <iconText>Stroke selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>


    <Action name="delete_keyframe">
      <icon></icon>
      <text>Delete keyframe</text>
      <whatsThis></whatsThis>
      <toolTip>Delete keyframe</toolTip>
      <iconText>Delete keyframe</iconText>
      <activationFlags>100000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>


  <Actions category="Window">
    <text>Window</text>
    <Action name="view_newwindow">
      <icon>window-new</icon>
      <text>&amp;New Window</text>
      <whatsThis></whatsThis>
      <toolTip>New Window</toolTip>
      <iconText>New Window</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="windows_next">
      <icon></icon>
      <text>N&amp;ext</text>
      <whatsThis></whatsThis>
      <toolTip>Next</toolTip>
      <iconText>Next</iconText>
      <activationFlags>10</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="windows_previous">
      <icon></icon>
      <text>Previous</text>
      <whatsThis></whatsThis>
      <toolTip>Previous</toolTip>
      <iconText>Previous</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="View">
    <text>View</text>
    <Action name="view_show_canvas_only">
      <icon>document-new</icon>
      <text>&amp;Show Canvas Only</text>
      <whatsThis></whatsThis>
      <toolTip>Show just the canvas or the whole window</toolTip>
      <iconText>Show Canvas Only</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Tab</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="fullscreen">
      <icon>view-fullscreen</icon>
      <text>F&amp;ull Screen Mode</text>
      <whatsThis></whatsThis>
      <toolTip>Display the window in full screen</toolTip>
      <iconText>Full Screen Mode</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+F</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_detached_canvas">
      <icon></icon>
      <text>Detach Canvas</text>
      <whatsThis></whatsThis>
      <toolTip>Show the canvas on a separate window</toolTip>
      <iconText>Detach Canvas</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="wrap_around_mode">
      <icon>wraparound</icon>
      <text>&amp;Wrap Around Mode</text>
      <whatsThis></whatsThis>
      <toolTip>Wrap Around Mode</toolTip>
      <iconText>Wrap Around Mode</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Shift+W</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="wrap_around_hv_axis">
      <icon>wraparound</icon>
      <text>Wrap Around Both Directions</text>
      <whatsThis></whatsThis>
      <toolTip>Wrap Around Both Directions</toolTip>
      <iconText>Wrap Around Both Directions</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="wrap_around_h_axis">
      <icon>wraparound</icon>
      <text>Wrap Around Horizontally</text>
      <whatsThis></whatsThis>
      <toolTip>Wrap Around Horizontally</toolTip>
      <iconText>Wrap Around Horizontally</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="wrap_around_v_axis">
      <icon>wraparound</icon>
      <text>Wrap Around Vertically</text>
      <whatsThis></whatsThis>
      <toolTip>Wrap Around Vertically</toolTip>
      <iconText>Wrap Around Vertically</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="level_of_detail_mode">
      <icon></icon>
      <text>&amp;Instant Preview Mode</text>
      <whatsThis></whatsThis>
      <toolTip>Instant Preview Mode</toolTip>
      <iconText>Instant Preview Mode</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Shift+L</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="softProof">
      <icon></icon>
      <text>Soft Proofing</text>
      <whatsThis></whatsThis>
      <toolTip>Turns on Soft Proofing</toolTip>
      <iconText>Turns on Soft Proofing</iconText>
      <shortcut>Ctrl+Y</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="gamutCheck">
      <icon></icon>
      <text>Out of Gamut Warnings</text>
      <whatsThis></whatsThis>
      <toolTip>Turns on warnings for colors out of proofed gamut, needs soft proofing to be turned on.</toolTip>
      <iconText>Turns on warnings for colors out of proofed gamut, needs soft proofing to be turned on.</iconText>
      <shortcut>Ctrl+Shift+Y</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="mirror_canvas">
      <icon>mirror-view</icon>
      <text>Mirror View</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror View</toolTip>
      <iconText>Mirror View</iconText>
      <shortcut>M</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="mirror_canvas_around_cursor">
      <icon>mirror-view-around-cursor</icon>
      <text>Mirror View Around Cursor</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror View Around Cursor</toolTip>
      <iconText>Mirror View Around Cursor</iconText>
      <shortcut>Alt+M</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
      <Action name="mirror_canvas_around_canvas">
      <icon>mirror-view</icon>
      <text>Mirror View Around Canvas</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror View Around Canvas</toolTip>
      <iconText>Mirror View Around Canvas</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="zoom_to_100pct">
      <icon>zoom-original</icon>
      <text>&amp;Zoom to 100%</text>
      <whatsThis></whatsThis>
      <toolTip>Zoom to 100%</toolTip>
      <iconText>Zoom to 100%</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+0</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_zoom_in">
      <icon>zoom-in</icon>
      <text>Zoom &amp;In</text>
      <whatsThis></whatsThis>
      <toolTip>Zoom In</toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl++</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_zoom_out">
      <icon>zoom-out</icon>
      <text>Zoom &amp;Out</text>
      <whatsThis></whatsThis>
      <toolTip>Zoom Out</toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+-</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="zoom_to_fit">
      <icon>zoom-fit-best</icon>
      <text>Fit to View</text>
      <whatsThis/>
      <toolTip>Fit Canvas to View</toolTip>
      <iconText>Fit to View</iconText>
      <shortcut/>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="zoom_to_fit_width">
      <icon>zoom-horizontal</icon>
      <text>Fit to View Width</text>
      <whatsThis/>
      <toolTip>Fit Canvas to View Width</toolTip>
      <iconText>Fit to View Width</iconText>
      <shortcut/>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="zoom_to_fit_height">
      <icon>zoom-vertical</icon>
      <text>Fit to View Height</text>
      <whatsThis/>
      <toolTip>Fit Canvas to View Height</toolTip>
      <iconText>Fit to View Height</iconText>
      <shortcut/>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="toggle_zoom_to_fit">
      <icon>zoom-fit-best</icon>
      <text>Toggle Fit to View</text>
      <whatsThis/>
      <toolTip>Toggle Fit to View</toolTip>
      <iconText>Toggle Fit to View</iconText>
      <shortcut/>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="rotate_canvas_right">
      <icon>rotate-canvas-right</icon>
      <text>Rotate &amp;Canvas Right</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Canvas Right</toolTip>
      <iconText>Rotate Canvas Right</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+]</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rotate_canvas_left">
      <icon>rotate-canvas-left</icon>
      <text>Rotate Canvas &amp;Left</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Canvas Left</toolTip>
      <iconText>Rotate Canvas Left</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+[</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="reset_canvas_rotation">
      <icon>rotation-reset</icon>
      <text>Reset Canvas Rotation</text>
      <whatsThis></whatsThis>
      <toolTip>Reset Canvas Rotation</toolTip>
      <iconText>Reset Canvas Rotation</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="reset_display">
      <icon>zoom-fit-best</icon>
      <text>Reset Display</text>
      <whatsThis/>
      <toolTip>Reset zoom, rotation, and mirroring to their default states.</toolTip>
      <iconText>Reset Display</iconText>
      <shortcut/>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="view_print_size">
      <icon>zoom-print</icon>
      <text>View Print Size</text>
      <whatsThis/>
      <toolTip>Map the canvas display to print size, based on the image resolution.</toolTip>
      <iconText>View Print Size</iconText>
      <shortcut/>
      <isCheckable>true</isCheckable>
      <statusTip/>
    </Action>
    <Action name="view_ruler">
      <icon></icon>
      <text>Show &amp;Rulers</text>
      <whatsThis>The rulers show the horizontal and vertical positions of the mouse on the image and can be used to position your mouse at the right place on the canvas. &lt;p>Uncheck this to hide the rulers.&lt;/p></whatsThis>
      <toolTip>Show Rulers</toolTip>
      <iconText>Show Rulers</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rulers_track_mouse">
      <icon></icon>
      <text>Rulers Track Pointer</text>
      <whatsThis>The rulers will track current mouse position and show it on screen. It can cause subtle performance slowdown</whatsThis>
      <toolTip>Rulers Track Pointer</toolTip>
      <iconText>Rulers Track Pointer</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_show_guides">
      <icon></icon>
      <text>Show Guides</text>
      <whatsThis></whatsThis>
      <toolTip>Show or hide guides</toolTip>
      <iconText>Show Guides</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_lock_guides">
      <icon></icon>
      <text>Lock Guides</text>
      <whatsThis></whatsThis>
      <toolTip>Lock or unlock guides</toolTip>
      <iconText>Lock Guides</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_snap_to_guides">
      <icon></icon>
      <text>Snap to Guides</text>
      <whatsThis></whatsThis>
      <toolTip>Snap cursor to guides position</toolTip>
      <iconText>Snap to Guides</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="showStatusBar">
      <icon></icon>
      <text>Show Status &amp;Bar</text>
      <whatsThis></whatsThis>
      <toolTip>Show or hide the status bar</toolTip>
      <iconText>Show Status Bar</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_pixel_grid">
      <icon></icon>
      <text>Show Pixel Grid</text>
      <whatsThis></whatsThis>
      <toolTip>Show Pixel Grid</toolTip>
      <iconText>Show Pixel Grid</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>1000</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_grid">
      <icon>view-grid</icon>
      <text>Show &amp;Grid</text>
      <whatsThis></whatsThis>
      <toolTip>Show Grid</toolTip>
      <iconText>Show Grid</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+'</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_snap_to_grid">
      <icon></icon>
      <text>Snap To Grid</text>
      <whatsThis></whatsThis>
      <toolTip>Snap To Grid</toolTip>
      <iconText>Snap To Grid</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut>Ctrl+Shift+;</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="show_snap_options_popup">
      <icon></icon>
      <text>Show Snap Options Popup</text>
      <whatsThis></whatsThis>
      <toolTip>Show Snap Options Popup</toolTip>
      <iconText>Show Snap Options Popup</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut>Shift+s</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_orthogonal">
      <icon></icon>
      <text>Snap Orthogonal</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Orthogonal</toolTip>
      <iconText>Snap Orthogonal</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_node">
      <icon></icon>
      <text>Snap Node</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Node</toolTip>
      <iconText>Snap Node</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_extension">
      <icon></icon>
      <text>Snap Extension</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Extension</toolTip>
      <iconText>Snap Extension</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_to_pixel">
      <icon></icon>
      <text>Snap Pixel</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Pixel</toolTip>
      <iconText>Snap Pixel</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_snap_intersection">
      <icon></icon>
      <text>Snap Intersection</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Intersection</toolTip>
      <iconText>Snap Intersection</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_bounding_box">
      <icon></icon>
      <text>Snap Bounding Box</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Bounding Box</toolTip>
      <iconText>Snap Bounding Box</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_image_bounds">
      <icon></icon>
      <text>Snap Image Bounds</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Image Bounds</toolTip>
      <iconText>Snap Image Bounds</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_snap_image_center">
      <icon></icon>
      <text>Snap Image Center</text>
      <whatsThis></whatsThis>
      <toolTip>Snap Image Center</toolTip>
      <iconText>Snap Image Center</iconText>
      <activationFlags>1000</activationFlags>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_toggle_painting_assistants">
      <icon></icon>
      <text>S&amp;how Painting Assistants</text>
      <whatsThis></whatsThis>
      <toolTip>Show Painting Assistants</toolTip>
      <iconText>Show Painting Assistants</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_toggle_assistant_previews">
      <icon></icon>
      <text>Show &amp;Assistant Previews</text>
      <whatsThis></whatsThis>
      <toolTip>Show Assistant Previews</toolTip>
      <iconText>Show Assistant Previews</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="view_toggle_reference_images">
      <icon></icon>
      <text>S&amp;how Reference Images</text>
      <whatsThis></whatsThis>
      <toolTip>Show Reference Images</toolTip>
      <iconText>Show Reference Images</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>

  </Actions>

  <Actions category="Image">
    <text>Image</text>
    <Action name="image_properties">
      <icon>document-properties</icon>
      <text context="Image Properties">&amp;Properties...</text>
      <whatsThis></whatsThis>
      <toolTip context="Image Properties">Properties</toolTip>
      <iconText context="Image Properties">Properties</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="image_color">
      <icon>format-stroke-color</icon>
      <text>&amp;Image Background Color and Transparency...</text>
      <whatsThis></whatsThis>
      <toolTip>Change the background color of the image</toolTip>
      <iconText>Image Background Color and Transparency</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="imagecolorspaceconversion">
      <icon></icon>
      <text>&amp;Convert Image Color Space...</text>
      <whatsThis></whatsThis>
      <toolTip>Convert Image Color Space</toolTip>
      <iconText>Convert Image Color Space</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="trim_to_image">
      <icon>trim-to-image</icon>
      <text>&amp;Trim to Image Size</text>
      <whatsThis></whatsThis>
      <toolTip>Trim to Image Size</toolTip>
      <iconText>Trim to Image Size</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="resizeimagetolayer">
      <icon></icon>
      <text>Trim to Current &amp;Layer</text>
      <whatsThis></whatsThis>
      <toolTip>Trim to Current Layer</toolTip>
      <iconText>Trim to Current Layer</iconText>
      <activationFlags>100000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="resizeimagetoselection">
      <icon></icon>
      <text>Trim to S&amp;election</text>
      <whatsThis></whatsThis>
      <toolTip>Trim to Selection</toolTip>
      <iconText>Trim to Selection</iconText>
      <activationFlags>100000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rotateimage">
      <icon></icon>
      <text>&amp;Rotate Image...</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Image</toolTip>
      <iconText>Rotate Image</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rotateImageCW90">
      <icon>object-rotate-right</icon>
      <text>Rotate &amp;Image 90° to the Right</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Image 90° to the Right</toolTip>
      <iconText>Rotate Image 90° to the Right</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rotateImageCCW90">
      <icon>object-rotate-left</icon>
      <text>Rotate Image &amp;90° to the Left</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Image 90° to the Left</toolTip>
      <iconText>Rotate Image 90° to the Left</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="rotateImage180">
      <icon></icon>
      <text>Rotate Image &amp;180°</text>
      <whatsThis></whatsThis>
      <toolTip>Rotate Image 180°</toolTip>
      <iconText>Rotate Image 180°</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="shearimage">
      <icon></icon>
      <text>&amp;Shear Image...</text>
      <whatsThis></whatsThis>
      <toolTip>Shear Image</toolTip>
      <iconText>Shear Image</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="mirrorImageHorizontal">
      <icon>symmetry-horizontal</icon>
      <text>&amp;Mirror Image Horizontally</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror Image Horizontally</toolTip>
      <iconText>Mirror Image Horizontally</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="mirrorImageVertical">
      <icon>symmetry-vertical</icon>
      <text>Mirror Image &amp;Vertically</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror Image Vertically</toolTip>
      <iconText>Mirror Image Vertically</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="imagesize">
      <icon></icon>
      <text>Scale Image To &amp;New Size...</text>
      <whatsThis></whatsThis>
      <toolTip>Scale Image To New Size</toolTip>
      <iconText>Scale Image To New Size</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Alt+I</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="offsetimage">
      <icon></icon>
      <text>&amp;Offset Image...</text>
      <whatsThis></whatsThis>
      <toolTip>Offset Image</toolTip>
      <iconText>Offset Image</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="canvassize">
      <icon></icon>
      <text>R&amp;esize Canvas...</text>
      <whatsThis></whatsThis>
      <toolTip>Resize Canvas</toolTip>
      <iconText>Resize Canvas</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Alt+C</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="imagesplit">
      <icon></icon>
      <text>Im&amp;age Split </text>
      <whatsThis></whatsThis>
      <toolTip>Image Split</toolTip>
      <iconText>Image Split</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="separate">
      <icon></icon>
      <text>Separate Ima&amp;ge...</text>
      <whatsThis></whatsThis>
      <toolTip>Separate Image</toolTip>
      <iconText>Separate Image</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="Select">
    <text>Select</text>
    <Action name="select_all">
      <icon>select-all</icon>
      <text>Select &amp;All</text>
      <whatsThis></whatsThis>
      <toolTip>Select All</toolTip>
      <iconText>Select All</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+A</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="deselect">
      <icon>select-clear</icon>
      <text>&amp;Deselect</text>
      <whatsThis></whatsThis>
      <toolTip>Deselect</toolTip>
      <iconText>Deselect</iconText>
      <activationFlags>1100000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+A</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="reselect">
      <icon></icon>
      <text>&amp;Reselect</text>
      <whatsThis></whatsThis>
      <toolTip>Reselect</toolTip>
      <iconText>Reselect</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+Shift+D</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="convert_to_vector_selection">
      <icon></icon>
      <text>&amp;Convert to Vector Selection</text>
      <whatsThis></whatsThis>
      <toolTip>Convert to Vector Selection</toolTip>
      <iconText>Convert to Vector Selection</iconText>
      <activationFlags>100000000000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="convert_to_raster_selection">
      <icon></icon>
      <text>&amp;Convert to Raster Selection</text>
      <whatsThis></whatsThis>
      <toolTip>Convert to Raster Selection</toolTip>
      <iconText>Convert to Raster Selection</iconText>
      <activationFlags>10000000000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edit_selection">
      <icon></icon>
      <text>Edit Selection</text>
      <whatsThis></whatsThis>
      <toolTip>Edit Selection</toolTip>
      <iconText>Edit Selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="convert_shapes_to_vector_selection">
      <icon></icon>
      <text>Convert Shapes to &amp;Vector Selection</text>
      <whatsThis></whatsThis>
      <toolTip>Convert Shapes to Vector Selection</toolTip>
      <iconText>Convert Shapes to Vector Selection</iconText>
      <activationFlags>1000000000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="featherselection">
      <icon></icon>
      <text>&amp;Feather Selection...</text>
      <whatsThis></whatsThis>
      <toolTip>Feather Selection</toolTip>
      <iconText>Feather Selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut>Shift+F6</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="toggle_display_selection">
      <icon></icon>
      <text>Dis&amp;play Selection</text>
      <whatsThis></whatsThis>
      <toolTip>Display Selection</toolTip>
      <iconText>Display Selection</iconText>
      <activationFlags>1000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+H</shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="selectionscale">
      <icon></icon>
      <text>Sca&amp;le...</text>
      <whatsThis></whatsThis>
      <toolTip>Scale</toolTip>
      <iconText>Scale</iconText>
      <activationFlags>100000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="colorrange">
      <icon></icon>
      <text>S&amp;elect from Color Range...</text>
      <whatsThis></whatsThis>
      <toolTip>Select from Color Range</toolTip>
      <iconText>Select from Color Range</iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="selectopaque">
      <icon></icon>
      <text>Select &amp;Opaque (Replace)</text>
      <whatsThis></whatsThis>
      <toolTip>Select Opaque</toolTip>
      <iconText>Select Opaque</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="selectopaque_add">
      <icon></icon>
      <text>Select Opaque (&amp;Add)</text>
      <whatsThis></whatsThis>
      <toolTip>Select Opaque (Add)</toolTip>
      <iconText>Select Opaque (Add)</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="selectopaque_subtract">
      <icon></icon>
      <text>Select Opaque (&amp;Subtract)</text>
      <whatsThis></whatsThis>
      <toolTip>Select Opaque (Subtract)</toolTip>
      <iconText>Select Opaque (Subtract)</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="selectopaque_intersect">
      <icon></icon>
      <text>Select Opaque (&amp;Intersect)</text>
      <whatsThis></whatsThis>
      <toolTip>Select Opaque (Intersect)</toolTip>
      <iconText>Select Opaque (Intersect)</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="growselection">
      <icon></icon>
      <text>&amp;Grow Selection...</text>
      <whatsThis></whatsThis>
      <toolTip>Grow Selection</toolTip>
      <iconText>Grow Selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="shrinkselection">
      <icon></icon>
      <text>S&amp;hrink Selection...</text>
      <whatsThis></whatsThis>
      <toolTip>Shrink Selection</toolTip>
      <iconText>Shrink Selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="borderselection">
      <icon></icon>
      <text>&amp;Border Selection...</text>
      <whatsThis></whatsThis>
      <toolTip>Border Selection</toolTip>
      <iconText>Border Selection</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="smoothselection">
      <icon></icon>
      <text>S&amp;mooth</text>
      <whatsThis></whatsThis>
      <toolTip>Smooth</toolTip>
      <iconText>Smooth</iconText>
      <activationFlags>10000000000</activationFlags>
      <activationConditions>100</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="Filter">
    <text>Filter</text>
    <Action name="filter_apply_again">
      <icon>filter-apply-again</icon>
      <text>&amp;Apply Filter Again</text>
      <whatsThis></whatsThis>
      <toolTip>Apply Filter Again</toolTip>
      <iconText>Apply Filter Again</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut>Ctrl+F</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="filter_apply_reprompt">
        <icon></icon>
        <text>Apply Filter Again (Reprompt)</text>
        <whatsThis></whatsThis>
        <toolTip>Reapply Last Used Filter with Prompt for Configuration</toolTip>
        <iconText>Reapply Last Used Filter with Prompt for Configuration</iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
    </Action>
    <Action name="adjust_filters">
      <icon></icon>
      <text>Adjust</text>
      <whatsThis></whatsThis>
      <toolTip>Adjust</toolTip>
      <iconText>Adjust</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="artistic_filters">
      <icon></icon>
      <text>Artistic</text>
      <whatsThis></whatsThis>
      <toolTip>Artistic</toolTip>
      <iconText>Artistic</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="blur_filters">
      <icon></icon>
      <text>Blur</text>
      <whatsThis></whatsThis>
      <toolTip>Blur</toolTip>
      <iconText>Blur</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="color_filters">
      <icon></icon>
      <text>Colors</text>
      <whatsThis></whatsThis>
      <toolTip>Colors</toolTip>
      <iconText>Colors</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="edge_filters">
      <icon></icon>
      <text>Edge Detection</text>
      <whatsThis></whatsThis>
      <toolTip>Edge Detection</toolTip>
      <iconText>Edge Detection</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="enhance_filters">
      <icon></icon>
      <text>Enhance</text>
      <whatsThis></whatsThis>
      <toolTip>Enhance</toolTip>
      <iconText>Enhance</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="emboss_filters">
      <icon></icon>
      <text>Emboss</text>
      <whatsThis></whatsThis>
      <toolTip>Emboss</toolTip>
      <iconText>Emboss</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="map_filters">
      <icon></icon>
      <text>Map</text>
      <whatsThis></whatsThis>
      <toolTip>Map</toolTip>
      <iconText>Map</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="other_filters">
      <icon></icon>
      <text>Other</text>
      <whatsThis></whatsThis>
      <toolTip>Other</toolTip>
      <iconText>Other</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="QMic">
      <icon>gmic</icon>
      <text>Start G'MIC-Qt</text>
      <whatsThis></whatsThis>
      <toolTip>Start G'Mic-Qt</toolTip>
      <iconText>Start G'Mic-Qt</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  <Action name="QMicAgain">
      <icon>gmic</icon>
      <text>Re-apply the last G'MIC filter</text>
      <whatsThis></whatsThis>
      <toolTip>Apply the last G'Mic-Qt action again</toolTip>
      <iconText>Apply the last G'Mic-Qt action again</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="Settings">
    <text>Settings</text>
    <Action name="options_configure">
      <icon>configure</icon>
      <text>&amp;Configure Krita...</text>
      <whatsThis></whatsThis>
      <toolTip>Configure Krita</toolTip>
      <iconText>Configure Krita</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="manage_bundles">
      <icon></icon>
      <text>&amp;Manage Resource Libraries...</text>
      <whatsThis></whatsThis>
      <toolTip>Manage Resource Libraries</toolTip>
      <iconText>Manage Resources Libraries</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="manage_resources">
      <icon></icon>
      <text>Manage Resources...</text>
      <whatsThis></whatsThis>
      <toolTip>Manage Resources</toolTip>
      <iconText>Manage Resources</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="switch_application_language">
      <icon>preferences-desktop-locale</icon>
      <text>Switch Application &amp;Language...</text>
      <whatsThis></whatsThis>
      <toolTip>Switch Application Language</toolTip>
      <iconText>Switch Application Language</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_toggledockers">
      <icon></icon>
      <text>&amp;Show Dockers</text>
      <whatsThis></whatsThis>
      <toolTip>Show Dockers</toolTip>
      <iconText>Show Dockers</iconText>
      <activationFlags>1</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="view_toggledockertitlebars">
      <icon></icon>
      <text>Sho&amp;w Docker Titlebars</text>
      <whatsThis></whatsThis>
      <toolTip>Show Docker Titlebars</toolTip>
      <iconText>Show Docker Titlebars</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>true</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="options_configure_toolbars">
      <icon>configure</icon>
      <text>Configure Tool&amp;bars...</text>
      <whatsThis></whatsThis>
      <toolTip>Configure Toolbars</toolTip>
      <iconText>Configure Toolbars</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="settings_dockers_menu">
      <icon></icon>
      <text>Dockers</text>
      <whatsThis></whatsThis>
      <toolTip>Dockers</toolTip>
      <iconText>Dockers</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="theme_menu">
      <icon></icon>
      <text>&amp;Themes</text>
      <whatsThis></whatsThis>
      <toolTip>Themes</toolTip>
      <iconText>Themes</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="style_menu">
      <icon></icon>
      <text>&amp;Styles</text>
      <whatsThis></whatsThis>
      <toolTip>Styles</toolTip>
      <iconText>Styles</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="settings_active_author">
      <icon>im-user</icon>
      <text>Active Author Profile</text>
      <whatsThis></whatsThis>
      <toolTip>Active Author Profile</toolTip>
      <iconText>Active Author Profile</iconText>
      <shortcut></shortcut>
      <isCheckable></isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="reset_configurations">
      <icon></icon>
      <text>Reset All Settings</text>
      <whatsThis></whatsThis>
      <toolTip>Reset All Settings to Default</toolTip>
      <iconText>Reset Settings</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="options_configure_keybinding">
      <icon>configure-shortcuts</icon>
      <text>Configure S&amp;hortcuts...</text>
      <whatsThis></whatsThis>
      <toolTip>Configure Shortcuts</toolTip>
      <iconText>Configure Shortcuts</iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="window">
      <icon></icon>
      <text>&amp;Window</text>
      <whatsThis></whatsThis>
      <toolTip>Window</toolTip>
      <iconText>Window</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="Help">
    <text>Help</text>
    <Action name="help_contents">
      <icon>help-contents</icon>
      <text>Krita &amp;Handbook</text>
      <whatsThis></whatsThis>
      <toolTip>Krita Handbook</toolTip>
      <iconText>Krita Handbook</iconText>
      <shortcut>F1</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="help_report_bug">
      <icon>tools-report-bug</icon>
      <text>&amp;Report Bug...</text>
      <whatsThis></whatsThis>
      <toolTip>Report Bug</toolTip>
      <iconText>Report Bug</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="help_about_app">
      <icon>krita</icon>
      <text>&amp;About Krita</text>
      <whatsThis></whatsThis>
      <toolTip>About Krita</toolTip>
      <iconText>About Krita</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="help_about_kde">
      <icon>kde</icon>
      <text>About &amp;KDE</text>
      <whatsThis></whatsThis>
      <toolTip>About KDE</toolTip>
      <iconText>About KDE</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>

  <Actions category="BrushesAndStuff">
    <text>Brushes and Stuff</text>
    <Action name="gradients">
      <icon></icon>
      <text>&amp;Gradients</text>
      <whatsThis></whatsThis>
      <toolTip>Gradients</toolTip>
      <iconText>Gradients</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="patterns">
      <icon></icon>
      <text>&amp;Patterns</text>
      <whatsThis></whatsThis>
      <toolTip>Patterns</toolTip>
      <iconText>Patterns</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="dual">
      <icon></icon>
      <text>&amp;Color</text>
      <whatsThis></whatsThis>
      <toolTip>Color</toolTip>
      <iconText>Color</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="chooseForegroundColor">
      <icon></icon>
      <text>&amp;Choose Foreground Color</text>
      <whatsThis></whatsThis>
      <toolTip>Choose Foreground Color</toolTip>
      <iconText>Choose Foreground Color</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="chooseBackgroundColor">
      <icon></icon>
      <text>&amp;Choose Background Color</text>
      <whatsThis></whatsThis>
      <toolTip>Choose Background Color</toolTip>
      <iconText>Choose Background Color</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="brushslider1">
      <icon></icon>
      <text>Brush option slider 1</text>
      <whatsThis></whatsThis>
      <toolTip>Brush option slider 1</toolTip>
      <iconText>Brush option slider 1</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="brushslider2">
      <icon></icon>
      <text>Brush option slider 2</text>
      <whatsThis></whatsThis>
      <toolTip>Brush option slider 2</toolTip>
      <iconText>Brush option slider 2</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="brushslider3">
      <icon></icon>
      <text>Brush option slider 3</text>
      <whatsThis></whatsThis>
      <toolTip>Brush option slider 3</toolTip>
      <iconText>Brush option slider 3</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
	<Action name="brushslider4">
      <icon></icon>
      <text>Brush option slider 4</text>
      <whatsThis></whatsThis>
      <toolTip>Brush option slider 4</toolTip>
      <iconText>Brush option slider 4</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="mirror_actions">
      <icon></icon>
      <text>Mirror</text>
      <whatsThis></whatsThis>
      <toolTip>Mirror</toolTip>
      <iconText>Mirror</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="select_layout">
      <icon></icon>
      <text>Layouts</text>
      <whatsThis></whatsThis>
      <toolTip>Select layout</toolTip>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    <Action name="workspaces">
      <icon></icon>
      <text>Workspaces</text>
      <whatsThis></whatsThis>
      <toolTip>Workspaces</toolTip>
      <iconText>Workspaces</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>


  </Actions>
</ActionCollection>
