# SPDX-FileCopyrightText: 2022 Nicolás Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'graphics/kseexpr': 'master'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kcrash': '@stable'

Options:
    use-ccache: True
