/* config-ocio.h.  Generated by cmake from config-ocio.h.cmake */

/* Define if you have ocio, the OpenColorIO Library */
#cmakedefine HAVE_OCIO 1

/* Define if OpenColorIO is v2.0 and higher */
#cmakedefine HAVE_OCIO_V2 1
