/* config-tiff.h.  Generated by cmake from config-tiff.h.cmake */

/* Define if libtiff defines TIFFTAG_IMAGESOURCEDATA and TIFFTAG_PHOTOSHOP */
#cmakedefine TIFF_HAS_PSD_TAGS 1

/* Define if libtiff accepts writing to TIFFTAG_IMAGESOURCEDATA and TIFFTAG_PHOTOSHOP */
#cmakedefine TIFF_CAN_WRITE_PSD_TAGS 1
