/* config-qmdiarea-always-show-subwindow-title.h.  Generated by cmake from config-qmdiarea-always-show-subwindow-title.h.cmake */

/* Define if you want to have QMdiArea::AlwaysShowSubwindowNameInTitleBar support */
#cmakedefine HAVE_QMDIAREA_ALWAYS_SHOW_SUBWINDOW_TITLE 1
