<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Hello">
  <Actions category="Hello">
    <text>Hello</text>
    <Action name="hello_python">
      <icon></icon>
      <text>Say Hello World</text>
      <whatsThis>Say Hello World</whatsThis>
      <toolTip>Say Hello World</toolTip>
      <iconText></iconText>
      <activationFlags></activationFlags>
      <activationConditions></activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
