<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">
    <text>Python Plugin Importer</text>

    <Action name="plugin_importer_file">
      <icon></icon>
      <text>Import Python Plugin from File...</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

    <Action name="plugin_importer_web">
      <icon></icon>
      <text>Import Python Plugin from Web...</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
</Actions>
</ActionCollection>
