name: krita
version: 4.2.6
summary: Krita is the digital painting studio for artists
description: Krita is a creative application for raster images. Whether you want to create
 from scratch or work with existing images, Krita is for you. You can work with
 photos or scanned images, or start with a blank slate. Krita supports most
 graphics tablets out of the box.
base: core18

apps:
  krita:
    command: qt5-launch usr/bin/krita
    plugs: [x11, unity7, home, opengl, network, network-bind, removable-media, desktop, desktop-legacy]

parts:
  krita:
    plugin: cmake
    configflags:
    - "-DCMAKE_INSTALL_PREFIX=/usr"
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DENABLE_TESTING=OFF"
    - "-DBUILD_TESTING=OFF"
    - "-DKDE_SKIP_TEST_SETTINGS=ON"
    source: https://download.kde.org/stable/krita/4.2.6/krita-4.2.6.tar.xz
# Use these instead to build from the git source
#    source: https://anongit.kde.org/krita.git
#    source-type: git
#    source-branch: master
    build-packages:
        - gettext
        - build-essential
        - cmake
        - libboost-dev
        - libboost-system-dev
        - libeigen3-dev
        - libexiv2-dev
        - libfftw3-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgl1-mesa-dev
        - libglew-dev
        - libglib2.0-dev
        - libglu1-mesa-dev
        - libgsf-1-dev
        - libgsl-dev
        - libjpeg-dev
        - liblcms2-dev
        - libopenexr-dev
        - libpng-dev
        - libpoppler-qt5-dev
        - libtiff5-dev
        - libvc-dev
        - libopencolorio-dev
        - libx11-dev
        - libxml2-dev
        - libxslt1-dev
        - libxi-dev
        - pkg-config
        - vc-dev
        - zlib1g-dev
        - libkf5kdcraw-dev
        - shared-mime-info
        - libopenimageio-dev
        - extra-cmake-modules
        - libkf5archive-dev
        - libkf5coreaddons-dev
        - libkf5guiaddons-dev
        - libkf5itemmodels-dev
        - libkf5itemviews-dev
        - libkf5widgetsaddons-dev
        - libkf5i18n-dev
        - libkf5windowsystem-dev
        - libkf5completion-dev
        - libkf5iconthemes-dev
        - libkf5kiocore5
        - libqt5svg5-dev
        - libqt5x11extras5-dev
        - libqt5opengl5-dev
        - libquazip5-dev
        - qtmultimedia5-dev
        - qtdeclarative5-dev
        - libkf5crash-dev

  runtime:
    plugin: nil
    stage-packages:
        - libexiv2-26
        - libfftw3-double3
        - libgomp1
        - libgsl23
        - libilmbase12
        - libjpeg8
        - liblcms2-2
        - libopencolorio1v5
        - libopenexr22
        - libpng16-16
        - libstdc++6
        - libtiff5
        - libx11-6
        - libxcb1
        - libxi6
        - zlib1g
        - libpoppler-qt5-1
        - shared-mime-info
        - libboost-system1.65.1
        - librtmp1
        - libqt5quickwidgets5
        - libkf5archive5
        - libkf5completion5
        - libkf5configcore5
        - libkf5configgui5
        - libkf5coreaddons5
        - libkf5guiaddons5
        - libkf5i18n5
        - libkf5itemviews5
        - libkf5widgetsaddons5
        - libkf5windowsystem5
        - libkf5crash5
        - libqt5concurrent5
        - libqt5core5a
        - libqt5dbus5
        - libqt5gui5
        - libqt5network5
        - libqt5printsupport5
        - libqt5svg5
        - libqt5widgets5
        - libqt5x11extras5
        - libqt5xml5
        - locales
        - libc-bin
        - libquazip5-1
        - libqt5quick5
        - libqt5quickparticles5
        - libqt5quickshapes5
        - qt5-qmltooling-plugins
        - libqt5qml5
        - libqt5multimedia5
        - libqt5multimediagsttools5
        - libqt5multimediaquick5
        - libqt5multimediawidgets5
    prime:
    - "-usr/share/wallpapers/*"
    - "-usr/share/fonts/*"

  plasma-integration:
    plugin: nil
    stage-packages:
    - plasma-integration
    - kde-style-breeze
    - breeze-icon-theme
    - kio # runtime slaves for kio
    prime:
    - "-usr/share/wallpapers/*"
    - "-usr/share/fonts/*"

  launcher:
    plugin: dump
    source: .
    organize:
      qt5-launch: bin/qt5-launch
      kf5-locale-gen: bin/kf5-locale-gen
