name: krita
grade: unstable
adopt-info: krita

base: core18
confinement: strict

apps:
  krita:
    common-id: org.kde.krita
    command: usr/bin/krita
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - removable-media
    environment:
      QT_QPA_PLATFORMTHEME: gtk3

layout:
  /usr/bin/ffmpeg:
    bind-file: $SNAP/usr/bin/ffmpeg

parts:
  libheif:
    plugin: autotools
    source: https://github.com/strukturag/libheif.git
    source-tag: v1.7.0
    build-packages:
      - libde265-dev
      - pkg-config
      - g++
      - libx265-dev
      - libjpeg8-dev
      - libpng-dev
    stage-packages:
      - libde265-0
      - libx265-146
      - libjpeg8
      - libpng16-16

  krita:
    after:
      - libheif
    source: https://download.kde.org/stable/krita/4.4.2/krita-4.4.2.tar.xz
    # # Use these instead to build from the git source
    # source: https://anongit.kde.org/krita.git
    # source-type: git
    # source-branch: master  
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DHIDE_SAFE_ASSERTS=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
    build-snaps: [kde-frameworks-5-core18-sdk]
    build-packages:
      - libboost-dev
      - libboost-system-dev
      - libeigen3-dev
      - libfftw3-dev
      - libgif-dev
      - libglew-dev
      - libgsf-1-dev
      - libgsl-dev
      - libjpeg-dev  # This is part of the sdk, but the build crashes if not included..
      - libopencolorio-dev
      - libopenexr-dev
      - libopenimageio-dev
      - libopenjp2-7-dev
      - libquazip5-dev
      - libraw-dev
      - libtiff-dev
      - libvc-dev
      - libx11-dev
      - libxi-dev
      - vc-dev
    parse-info: [usr/share/metainfo/org.kde.krita.appdata.xml]


  runtime:
    plugin: nil
    stage-packages:
      - freeglut3 
      - libboost-system1.65.1
      - libfftw3-double3
      - libgif7
      - libgsl23
      - libgslcblas0
      - libilmbase12
      - libopencolorio1v5
      - libopenexr22
      - libquazip5-1
      - libraw16
      - libtinyxml2.6.2v5
      - libxi6
      - libyaml-cpp0.5v5
      - zlib1g
      # Required for rendering animations
      - ffmpeg
      - libglu1-mesa
      - libslang2
    prime:
      - "-usr/share/fonts/*"
      # libquazip5-1 pulls in Qt5 from bionic as a dependency. We don't
      # want it in our snap, however, because we get a newer Qt5 from the
      # kde-kf5 platform snap.
      - "-usr/lib/x86_64-linux-gnu/libQt5*"
      - "-usr/lib/x86_64-linux-gnu/libqt5*"

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - krita
      - runtime
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - kde-frameworks-5-core18
    override-prime: |
      set -eux
      for snap in "core18" "kde-frameworks-5-core18"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
