######################################################################
# Automatically generated by qmake (2.01a) Sun May 10 20:34:30 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../kis_tile.h ../../kis_tile_data.h ../../kis_tile_data_store.h
SOURCES += ../../kis_tile.cc \
           ../../kis_tile_data.cc \
           ../../kis_tile_data_store.cc \
           main.cc
