/* config-qt_x11_p.h  Generated by cmake from config-qt_x11_p.h.cmake */

#ifndef CONFIG_QT_X11_P_H_
#define CONFIG_QT_X11_P_H_

#cmakedefine HAVE_SYSTEM_PRIVATE_HEADERS @HAVE_SYSTEM_PRIVATE_HEADERS@

#if HAVE_SYSTEM_PRIVATE_HEADERS == 1
#define QT_NO_XIM
#include <qt_x11_p.h>
#undef QT_NO_XIM
#else

#warning "Using hard-copied Qt private headers! Tablet may not work at all!"
#if QT_VERSION >= 0x040800
#include <input/wintab/qt_x11_p_qt48.h>
#else
#include <input/wintab/qt_x11_p_qt47.h>
#endif

#endif


#endif /* CONFIG_QT_X11_P_H_ */
