<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="SVG Tools">
  <Actions category="Text Tool">
    <text>SVG Text Tool</text>
    <Action name="SvgTextTool">
      <icon>draw-text</icon>
      <text>Text Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Text Tool</toolTip>
      <iconText>Text Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip/>
    </Action>
    <Action name="svg_format_textcolor">
      <iconText>Text Color</iconText>
      <shortcut/>
      <toolTip>Text Color...</toolTip>
      <icon>format-text-color</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Text Color</text>
    </Action>
    <Action name="svg_background_color">
      <iconText>Background</iconText>
      <shortcut/>
      <toolTip>Background Color...</toolTip>
      <icon>format-fill-color</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Background</text>
    </Action>
    <Action name="svg_font_size">
      <iconText>Font Size</iconText>
      <shortcut/>
      <toolTip>Font Size</toolTip>
      <icon/>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Font Size</text>
    </Action>
    <Action name="svg_font">
      <iconText>Font...</iconText>
      <shortcut>Ctrl+Alt+F</shortcut>
      <toolTip>Change character size, font, boldface, italics etc.</toolTip>
      <icon/>
      <whatsThis>Change the attributes of the currently selected characters.</whatsThis>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Font...</text>
    </Action>
    <Action name="svg_insert_special_character">
      <iconText>Special Character...</iconText>
      <shortcut>Alt+Shift+C</shortcut>
      <toolTip>Insert one or more symbols or characters not found on the keyboard</toolTip>
      <icon>character-set</icon>
      <whatsThis>Insert one or more symbols or characters not found on the keyboard.</whatsThis>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Special Character...</text>
    </Action>
    <Action name="svg_align_right">
      <iconText>Align Right</iconText>
      <shortcut>Ctrl+Alt+R</shortcut>
      <toolTip>Align Right</toolTip>
      <icon>format-justify-right</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Align Right</text>
    </Action>
    <Action name="svg_align_left">
      <iconText>Align Left</iconText>
      <shortcut/>
      <toolTip>Align Left</toolTip>
      <icon>format-justify-left</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Align Left</text>
    </Action>
    <Action name="svg_align_justified">
      <iconText>Align Block</iconText>
      <shortcut>Ctrl+Alt+R</shortcut>
      <toolTip>Align Block</toolTip>
      <icon>format-justify-fill</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Align Block</text>
    </Action>
    <Action name="svg_align_center">
      <iconText>Align Center</iconText>
      <shortcut>Ctrl+Alt+C</shortcut>
      <toolTip>Align Center</toolTip>
      <icon>format-justify-center</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Align Center</text>
    </Action>
    <Action name="svg_decrease_font_size">
      <iconText>Decrease Font Size</iconText>
      <shortcut>Ctrl+&lt;</shortcut>
      <toolTip>Decrease Font Size</toolTip>
      <icon/>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Decrease Font Size</text>
    </Action>
    <Action name="svg_increase_font_size">
      <iconText>Increase Font Size</iconText>
      <shortcut>Ctrl+&gt;</shortcut>
      <toolTip>Increase Font Size</toolTip>
      <icon/>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Increase Font Size</text>
    </Action>
    <Action name="svg_format_subscript">
      <iconText>Subscript</iconText>
      <shortcut>Ctrl+Shift+B</shortcut>
      <toolTip>Subscript</toolTip>
      <icon>format-text-subscript</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Subscript</text>
    </Action>
    <Action name="svg_format_superscript">
      <iconText>Superscript</iconText>
      <shortcut>Ctrl+Shift+P</shortcut>
      <toolTip>Superscript</toolTip>
      <icon>format-text-superscript</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Superscript</text>
    </Action>
    <Action name="svg_format_underline">
      <iconText>Underline</iconText>
      <shortcut>Ctrl+U</shortcut>
      <toolTip>Underline</toolTip>
      <icon>format-text-underline</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Underline</text>
    </Action>
    <Action name="svg_format_strike_through">
      <iconText>Strikethrough</iconText>
      <shortcut/>
      <toolTip>Strikethrough</toolTip>
      <icon>format-text-strikethrough</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Strikethrough</text>
    </Action>
    <Action name="svg_weight_bold">
      <iconText>Bold</iconText>
      <shortcut>Ctrl+B</shortcut>
      <toolTip>Bold</toolTip>
      <icon>format-text-bold</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Bold</text>
    </Action>
    <Action name="svg_format_italic">
      <iconText>Italic</iconText>
      <shortcut>Ctrl+I</shortcut>
      <toolTip>Italic</toolTip>
      <icon>format-text-italic</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Italic</text>
    </Action>
    <Action name="svg_weight_normal">
      <iconText>Normal</iconText>
      <shortcut>Ctrl+N</shortcut>
      <toolTip>Normal</toolTip>
      <icon>format-text-normal</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Normal</text>
    </Action>
    <Action name="svg_weight_demi">
      <iconText>Demi</iconText>
      <shortcut/>
      <toolTip>Demi</toolTip>
      <icon>format-text-demi</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Demi</text>
    </Action>
    <Action name="svg_weight_black">
      <iconText>Black</iconText>
      <shortcut/>
      <toolTip>Black</toolTip>
      <icon>format-text-black</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Black</text>
    </Action>
    <Action name="svg_weight_light">
      <iconText>Light</iconText>
      <shortcut>Ctrl+L</shortcut>
      <toolTip>Light</toolTip>
      <icon>format-text-light</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Light</text>
    </Action>
    <Action name="svg_line_height">
      <iconText>Line Height</iconText>
      <shortcut>Ctrl+H</shortcut>
      <toolTip>Line Height in em</toolTip>
      <icon></icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Line Height</text>
    </Action>
    <Action name="svg_settings">
      <iconText>Settings</iconText>
      <shortcut></shortcut>
      <toolTip>Text Editor Settings</toolTip>
      <icon></icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text context="Text Editor Settings label">Settings...</text>
    </Action>
    <Action name="svg_sample_color">
      <iconText>Color Sampler</iconText>
      <shortcut></shortcut>
      <toolTip>Sample a color from the screen</toolTip>
      <icon></icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
      <text>Color Sampler</text>
    </Action>
    <Action name="svg_font_kerning">
      <iconText>Kerning</iconText>
      <shortcut></shortcut>
      <toolTip>Kerning</toolTip>
      <icon>kerning</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
      <text>Kerning</text>
    </Action>
    </Actions>
</ActionCollection>
