######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 22:03:40 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lQtXml

# Input
SOURCES += xml2matlab.cpp
