#defines the set of products commonly wanted for Calligra Active

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    ACTIVE
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
    PLUGIN_FORMULASHAPE
    PLUGIN_VECTORSHAPE
)
