#defines the set of products commonly wanted for Calligra Active

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    ACTIVE
# extras
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
# plugins
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
    PLUGIN_FORMULASHAPE
    PLUGIN_VECTORSHAPE
    PLUGIN_VIDEOSHAPE
# filters
    FILTER_XLSX_TO_ODS
    FILTER_XLS_TO_SHEETS
    FILTER_CSV_TO_SHEETS
    FILTER_APPLIXSPREAD_TO_KSPREAD
    FILTER_DBASE_TO_KSPREAD
    FILTER_GNUMERIC_TO_SHEETS
    FILTER_OPENCALC_TO_SHEETS
    FILTER_QUATTROPRO_TO_SHEETS
    FILTER_HTML_TO_ODS
    FILTER_KPR_TO_OPD
    FILTER_PPT_TO_ODP
    FILTER_PPTX_TO_ODP
    FILTER_DOC_TO_ODT
    FILTER_DOCX_TO_ODT
    FILTER_WORDPERFECT_TO_ODT
    FILTER_WORKS_TO_ODT
    FILTER_APPLIXWORD_TO_ODT
    FILTER_ASCII_TO_WORDS
    FILTER_RTF_TO_ODT
)
