#defines the set of products commonly wanted by Creationists ;)

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    KARBON
    KRITA
    CONVERTER
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
    EXTRA_QUICKPRINT
    PLUGIN_COLORENGINES
    PLUGIN_SPACENAVIGATOR
    PLUGIN_ARTISTICTEXTSHAPE
    PLUGIN_DOCKERS
    PLUGIN_TEXTEDITING
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
)
