#defines the set of products commonly wanted by Creationists ;)

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    KARBON
    KRITA
    CONVERTER
# extras
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
    EXTRA_QUICKPRINT
# plugins
    PLUGIN_COLORENGINES
    PLUGIN_SPACENAVIGATOR
    PLUGIN_ARTISTICTEXTSHAPE
    PLUGIN_DOCKERS
    PLUGIN_TEXTEDITING
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
# filters
    FILTER_EPS_TO_SVG_AI
    FILTER_XFIG_TO_ODG
    FILTER_PDF_TO_SVG
    FILTER_WPG_TO_SVG
    FILTER_KARBON_TO_IMAGE
    FILTER_KARBON_TO_SVG
    FILTER_SVG_TO_KARBON
    FILTER_KARBON_TO_WMF
    FILTER_WMF_TO_SVG
    FILTER_KARBON1X_TO_KARBON
)
