# Krita-only set of tools

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    KRITA
    CONVERTER
# extras
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
    EXTRA_QUICKPRINT
# plugins
    PLUGIN_COLORENGINES
    PLUGIN_SPACENAVIGATOR
    PLUGIN_ARTISTICTEXTSHAPE
    PLUGIN_DOCKERS
    PLUGIN_TEXTEDITING
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
)
