#defines the set of products commonly wanted for classic Desktop environment

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
# apps
    AUTHOR
    FLOW
    KEXI
    KRITA
    SHEETS
    STAGE
    WORDS
# plugins
    PLUGIN_COLORENGINES
    PLUGIN_MUSICSHAPE
    PLUGIN_ARTISTICTEXTSHAPE
    PLUGIN_DOCKERS
    PLUGIN_TEXTEDITING
    PLUGIN_KEXI_SPREADSHEETMIGRATION
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
    PLUGIN_FORMULASHAPE
    PLUGIN_VECTORSHAPE
    PLUGIN_REPORTING
# feature
    SCRIPTING
# extras
    CALLIGRA
    CONVERTER
    EXTRA_PROPERTIES
    EXTRA_THUMBNAIL
    EXTRA_QUICKPRINT
)
