/*
 *  Copyright (c) 1999-2000 Matthias Elter  <me@kde.org>
 *  Copyright (c) 2003-2014 Boudewijn Rempt <boud@valdyas.org>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include "kis_aboutdata.h"

#include <klocale.h>
#include <calligraversion.h>
#include <calligragitversion.h>
#include <KoIcon.h>

KAboutData *newKritaAboutData()
{
    QString calligraVersion(CALLIGRA_VERSION_STRING);
    QString version;


#ifdef CALLIGRA_GIT_SHA1_STRING
    QString gitVersion(CALLIGRA_GIT_SHA1_STRING);
    version = QString("%1 (git %2)").arg(calligraVersion).arg(gitVersion).toLatin1();
#else
    version = calligraVersion;
#endif

    KAboutData * aboutData = new KAboutData("krita",
                                            i18n("Krita"),
                                            version.toLatin1(),
                                            i18n("Digital Painting for Artists"),
                                            KAboutLicense::GPL_V2,
                                            i18n("© 1999-%1, The Krita Team").arg(CALLIGRA_YEAR),
                                            QString(),
                                            "http://www.krita.org",
                                            "submit@bugs.kde.org");

    aboutData->setProgramIconName(koIconName("calligrakrita"));

    aboutData->addAuthor(i18n("Boudewijn Rempt"), i18n("Project Maintainer"));
    aboutData->addAuthor(i18n("Aaron J. Seigo"));
    aboutData->addAuthor(i18n("Adam Celarek"));
    aboutData->addAuthor(i18n("Adam Pigg"));
    aboutData->addAuthor(i18n("Adriaan de Groot"));
    aboutData->addAuthor(i18n("Adrian Page"));
    aboutData->addAuthor(i18n("Adrian Schroeter"));
    aboutData->addAuthor(i18n("Albert Astals Cid"));
    aboutData->addAuthor(i18n("Alberto Villa"));
    aboutData->addAuthor(i18n("Alexander Neundorf"));
    aboutData->addAuthor(i18n("Alexander Potashev"));
    aboutData->addAuthor(i18n("Alexis Ménard"));
    aboutData->addAuthor(i18n("Alfredo Beaumont Sainz"));
    aboutData->addAuthor(i18n("Allen Winter"));
    aboutData->addAuthor(i18n("Ana Beatriz Guerrero López"));
    aboutData->addAuthor(i18n("Andras Mantia"));
    aboutData->addAuthor(i18n("Andreas Hartmetz"));
    aboutData->addAuthor(i18n("Andreas Lundin"));
    aboutData->addAuthor(i18n("André Marcelo Alvarenga"));
    aboutData->addAuthor(i18n("Andrew Coles"));
    aboutData->addAuthor(i18n("Andre Woebbeking"));
    aboutData->addAuthor(i18n("Andrius da Costa Ribas"));
    aboutData->addAuthor(i18n("Andy Fawcett"));
    aboutData->addAuthor(i18n("Anne-Marie Mahfouf"));
    aboutData->addAuthor(i18n("Ariya Hidayat"));
    aboutData->addAuthor(i18n("Arjen Hiemstra"));
    aboutData->addAuthor(i18n("Bart Coppens"));
    aboutData->addAuthor(i18n("Ben Cooksley"));
    aboutData->addAuthor(i18n("Benjamin K. Stuhl"));
    aboutData->addAuthor(i18n("Benjamin Meyer"));
    aboutData->addAuthor(i18n("Benjamin Reed"));
    aboutData->addAuthor(i18n("Benoît Jacob"));
    aboutData->addAuthor(i18n("Ben Schleimer"));
    aboutData->addAuthor(i18n("Bernhard Rosenkraenzer"));
    aboutData->addAuthor(i18n("Bo Thorsen"));
    aboutData->addAuthor(i18n("Brad Hards"));
    aboutData->addAuthor(i18n("Bram Schoenmakers"));
    aboutData->addAuthor(i18n("Burkhard Lück"));
    aboutData->addAuthor(i18n("Carlo Segato"));
    aboutData->addAuthor(i18n("C. Boemann"));
    aboutData->addAuthor(i18n("Christer Stenbrenden"));
    aboutData->addAuthor(i18n("Christian Ehrlicher"));
    aboutData->addAuthor(i18n("Christian Mueller"));
    aboutData->addAuthor(i18n("Christoph Feck"));
    aboutData->addAuthor(i18n("Chusslove Illich"));
    aboutData->addAuthor(i18n("Clarence Dang"));
    aboutData->addAuthor(i18n("Cyrille Berger"));
    aboutData->addAuthor(i18n("Daniel M. Duley"));
    aboutData->addAuthor(i18n("Daniel Molkentin"));
    aboutData->addAuthor(i18n("Dan Leinir Turthra Jensen"));
    aboutData->addAuthor(i18n("Dan Meltzer"));
    aboutData->addAuthor(i18n("Danny Allen"));
    aboutData->addAuthor(i18n("David Faure"));
    aboutData->addAuthor(i18n("David Gowers"));
    aboutData->addAuthor(i18n("Dirk Mueller"));
    aboutData->addAuthor(i18n("Dirk Schönberger"));
    aboutData->addAuthor(i18n("Dmitry Kazakov"));
    aboutData->addAuthor(i18n("Edward Apap"));
    aboutData->addAuthor(i18n("Elvis Stansvik"));
    aboutData->addAuthor(i18n("Emanuele Tamponi"));
    aboutData->addAuthor(i18n("Enrique Matías Sánchez"));
    aboutData->addAuthor(i18n("Fabian Kosmale"));
    aboutData->addAuthor(i18n("Frank Osterfeld"));
    aboutData->addAuthor(i18n("Frederik Schwarzer"));
    aboutData->addAuthor(i18n("Fredrik Edemar"));
    aboutData->addAuthor(i18n("Fredy Yanardi"));
    aboutData->addAuthor(i18n("Friedrich W. H. Kossebau"));
    aboutData->addAuthor(i18n("Gábor Lehel"));
    aboutData->addAuthor(i18n("Gary Cramblitt"));
    aboutData->addAuthor(i18n("Geoffry Song"));
    aboutData->addAuthor(i18n("Gioele Barabucci"));
    aboutData->addAuthor(i18n("Giovanni Venturi"));
    aboutData->addAuthor(i18n("Gopalakrishna Bhat A"));
    aboutData->addAuthor(i18n("Hanna Scott"));
    aboutData->addAuthor(i18n("Harald Sitter"));
    aboutData->addAuthor(i18n("Hasso Tepper"));
    aboutData->addAuthor(i18n("Helge Deller"));
    aboutData->addAuthor(i18n("Helio Castro"));
    aboutData->addAuthor(i18n("Hideki Saito"));
    aboutData->addAuthor(i18n("Hoàng Đức Hiếu"));
    aboutData->addAuthor(i18n("Hugo Pereira Da Costa"));
    aboutData->addAuthor(i18n("Inge Wallin"));
    aboutData->addAuthor(i18n("Ingo Klöcker"));
    aboutData->addAuthor(i18n("İsmail Dönmez"));
    aboutData->addAuthor(i18n("Ivan Yossi"));
    aboutData->addAuthor(i18n("Jaime"));
    aboutData->addAuthor(i18n("Jaime Torres"));
    aboutData->addAuthor(i18n("Jaison Lee"));
    aboutData->addAuthor(i18n("Jakob Petsovits"));
    aboutData->addAuthor(i18n("Jakub Stachowski"));
    aboutData->addAuthor(i18n("Jan Hambrecht"));
    aboutData->addAuthor(i18n("Jarosław Staniek"));
    aboutData->addAuthor(i18n("Jens Herden"));
    aboutData->addAuthor(i18n("Jessica Hall"));
    aboutData->addAuthor(i18n("Johannes Simon"));
    aboutData->addAuthor(i18n("John Layt"));
    aboutData->addAuthor(i18n("Jonathan Riddell"));
    aboutData->addAuthor(i18n("Jonathan Singer"));
    aboutData->addAuthor(i18n("José Luis Vergara"));
    aboutData->addAuthor(i18n("Juan Luis Boya García"));
    aboutData->addAuthor(i18n("Juan Palacios"));
    aboutData->addAuthor(i18n("Jure Repinc"));
    aboutData->addAuthor(i18n("Kai-Uwe Behrmann"));
    aboutData->addAuthor(i18n("Kevin Krammer"));
    aboutData->addAuthor(i18n("Kevin Ottens"));
    aboutData->addAuthor(i18n("Kurt Pfeifle"));
    aboutData->addAuthor(i18n("Laurent Montel"));
    aboutData->addAuthor(i18n("Lauri Watts"));
    aboutData->addAuthor(i18n("Leo Savernik"));
    aboutData->addAuthor(i18n("Lukáš Tinkl"));
    aboutData->addAuthor(i18n("Lukáš Tvrdý"));
    aboutData->addAuthor(i18n("Maciej Mrozowski"));
    aboutData->addAuthor(i18n("Malcolm Hunter"));
    aboutData->addAuthor(i18n("Manuel Riecke"));
    aboutData->addAuthor(i18n("manu tortosa"));
    aboutData->addAuthor(i18n("Marc Pegon"));
    aboutData->addAuthor(i18n("Marijn Kruisselbrink"));
    aboutData->addAuthor(i18n("Martin Ellis"));
    aboutData->addAuthor(i18n("Martin Gräßlin"));
    aboutData->addAuthor(i18n("Matthew Woehlke"));
    aboutData->addAuthor(i18n("Matthias Klumpp"));
    aboutData->addAuthor(i18n("Matthias Kretz"));
    aboutData->addAuthor(i18n("Matus Talcik"));
    aboutData->addAuthor(i18n("Maximiliano Curia"));
    aboutData->addAuthor(i18n("Melchior Franz"));
    aboutData->addAuthor(i18n("Michael David Howell"));
    aboutData->addAuthor(i18n("Michael Drueing"));
    aboutData->addAuthor(i18n("Michael Thaler"));
    aboutData->addAuthor(i18n("Michel Hermier"));
    aboutData->addAuthor(i18n("Mohit Goyal"));
    aboutData->addAuthor(i18n("Mojtaba Shahi Senobari"));
    aboutData->addAuthor(i18n("Montel Laurent"));
    aboutData->addAuthor(i18n("Nick Shaforostoff"));
    aboutData->addAuthor(i18n("Nicolas Goutte"));
    aboutData->addAuthor(i18n("Olivier Goffart"));
    aboutData->addAuthor(i18n("Patrick Julien"));
    aboutData->addAuthor(i18n("Patrick Spendrin"));
    aboutData->addAuthor(i18n("Pavel Heimlich"));
    aboutData->addAuthor(i18n("Peter Simonsson"));
    aboutData->addAuthor(i18n("Pierre Ducroquet"));
    aboutData->addAuthor(i18n("Pierre Stirnweiss"));
    aboutData->addAuthor(i18n("Pino Toscano"));
    aboutData->addAuthor(i18n("Rafael Fernández López"));
    aboutData->addAuthor(i18n("Raphael Langerhorst"));
    aboutData->addAuthor(i18n("Rex Dieter"));
    aboutData->addAuthor(i18n("Rob Buis"));
    aboutData->addAuthor(i18n("Roopesh Chander"));
    aboutData->addAuthor(i18n("Sahil Nagpal"));
    aboutData->addAuthor(i18n("Salil Kapur"));
    aboutData->addAuthor(i18n("Samuel Buttigieg"));
    aboutData->addAuthor(i18n("Sander Koning"));
    aboutData->addAuthor(i18n("Sascha Suelzer"));
    aboutData->addAuthor(i18n("Scott Petrovic"));
    aboutData->addAuthor(i18n("Scott Wheeler"));
    aboutData->addAuthor(i18n("Sebastian Sauer"));
    aboutData->addAuthor(i18n("Shivaraman Aiyer"));
    aboutData->addAuthor(i18n("Siddharth Sharma"));
    aboutData->addAuthor(i18n("Silvio Heinrich"));
    aboutData->addAuthor(i18n("Somsubhra Bairi"));
    aboutData->addAuthor(i18n("Spencer Brown"));
    aboutData->addAuthor(i18n("Srikanth Tiyyagura"));
    aboutData->addAuthor(i18n("Stefan Nikolaus"));
    aboutData->addAuthor(i18n("Stephan Binner"));
    aboutData->addAuthor(i18n("Stephan Kulow"));
    aboutData->addAuthor(i18n("Stuart Dickson"));
    aboutData->addAuthor(i18n("Sune Vuorela"));
    aboutData->addAuthor(i18n("Sven Langkamp"));
    aboutData->addAuthor(i18n("Thiago Macieira"));
    aboutData->addAuthor(i18n("Thomas Capricelli"));
    aboutData->addAuthor(i18n("Thomas Friedrichsmeier"));
    aboutData->addAuthor(i18n("Thomas Klausner"));
    aboutData->addAuthor(i18n("Thomas Nagy"));
    aboutData->addAuthor(i18n("Thomas Zander"));
    aboutData->addAuthor(i18n("Thorsten Staerk"));
    aboutData->addAuthor(i18n("Thorsten Zachmann"));
    aboutData->addAuthor(i18n("Tim Beaulen"));
    aboutData->addAuthor(i18n("Timothée Giet"));
    aboutData->addAuthor(i18n("Tobias Koenig"));
    aboutData->addAuthor(i18n("Tom Burdick"));
    aboutData->addAuthor(i18n("Torio Mlshi"));
    aboutData->addAuthor(i18n("Torsten Rahn"));
    aboutData->addAuthor(i18n("Unai Garro"));
    aboutData->addAuthor(i18n("Urs Wolfer"));
    aboutData->addAuthor(i18n("Vadim Zhukov"));
    aboutData->addAuthor(i18n("Vera Lukman"));
    aboutData->addAuthor(i18n("Victor Lafon"));
    aboutData->addAuthor(i18n("Volker Krause"));
    aboutData->addAuthor(i18n("Waldo Bastian"));
    aboutData->addAuthor(i18n("Werner Trobin"));
    aboutData->addAuthor(i18n("Wilco Greven"));
    aboutData->addAuthor(i18n("Will Entriken"));
    aboutData->addAuthor(i18n("William Steidtmann"));
    aboutData->addAuthor(i18n("Wolthera van Hovell"));
    aboutData->addAuthor(i18n("Yann Bodson"));
    aboutData->addAuthor(i18n("Yue Liu"));
    aboutData->addAuthor(i18n("Yuri Chornoivan"));

    aboutData->addCredit(i18n("Peter Sikking"), i18n("Project Vision"));
    aboutData->addCredit(i18n("Ramon Miranda"), i18n("Artist, Muses author, brush and preset creator"));
    aboutData->addCredit(i18n("David Revoy"), i18n("Brushes and Palettes"));
    aboutData->addCredit(i18n("Ilya Portnov"), i18n("MyPaint shade selector"));
    aboutData->addCredit(i18n("Martin Renold"), i18n("MyPaint shade selector"));
    aboutData->addCredit(i18n("Sander Koning"), i18n("Icon Management"));

    aboutData->addCredit(i18n("マイキ"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("4lun"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("A. Agarossi"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("A. Alexeev"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Adam J Dunn"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Alexander Haskell"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Alicia Rangel Avila"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Allan Nordhøy"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Alvaro F. Celis"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Anatoliy Sova"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Andreas Rieger"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Andres"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Andrew Buttery,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Andrew Helm"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Antonio Díaz"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Armin Halac"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Arne Brix"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Arran Langmead"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Arturo Jose Perez Verdu"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("AsavarTzeth"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Axel Philipsenburg"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Balloontree"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bartek Moniewski"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bastian"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("BenBen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("BenjiButo"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bente Iren Larsen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bill Travis"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bla6,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("blendtuts.com"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bogdan Covaciu"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Børre Gaup"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Bosse \"Melkesedek\" Jönsson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Brad Auty"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Brian Hinton"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("B.Tolputt,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Camelworks"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Carlos Andrés Moscoso"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Carlos Mazon"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Champagnie"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Charles Prescott Collins IV"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Charles Stanhope,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("chartus"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Chris Impink"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Chris Nutt"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Christian Lange"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Christian Leon Christensen @chrleon"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Christina K"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Christophe"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Carré"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("chronichol"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("corien klapwijk"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("CPau"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Cristiano Seixas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("C.Rogers"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("cycl0ne"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daddle"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("DaisyBuns"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("damousey,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daniel Aleksandersen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daniel Bull"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daniel Pinheiro Lima"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Danni Coy"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daryl Sautter"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Covert"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Goemans,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Herrmann"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Macara"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Plassmann"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Prommer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David R"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Revoy"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("David Shere"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Daxi Forerunner"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("denDwaler"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Deni Klapka"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dezponia Veil"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dinesh Kumar"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("DIT"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ditte Mark Kreinøe"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dmitri \"D-Meat\" Engman"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dmitriy Savin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Don Smith"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("D. Sky Rains"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dustin Morabito"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Dutch_Wolf"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Duy Vo Van"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("D Wray"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("DzymatoR,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("edomaur"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Edward Coughlan"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Eeku Koponen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Egor Nelyubov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Eike Hein"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Elie Morisse"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Elizabeth Barndollar,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Elyaradine"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Eo Fenstalker"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Érico Vieira Porto"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Erik Johansson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("ethan calabria"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Exilist - S.Grundmann"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Fabian Schempp"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Farkas Máté"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Felicia Nørregård"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Fernando Tortosa"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Florian Jacob"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Foli Ayivoh"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Formanor"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Francesca \"JK\" Poppi"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("François Coulon"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Frank Bremer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Frédéric Momméja"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Frederik Gladhorn"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Frodolf"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Fuzzyman"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Gábor Udvari"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("gabsd84"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Gamamoto"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Gareth Davidson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Gary Thomas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("gcala"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("geeky"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Georg Piorczynski"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Giant Oak Studios"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Gibonus,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Giovanni Bianco"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Giovanni Remigi"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("GNX"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("goda87"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Grant Borodin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Grégory Fauchille"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Grigory Petrov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("gummiwaffen,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("GustavN"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hayashihikaru"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Heather Blandford"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hector Dubon"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("higekzk"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("High Iron Studios"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hiroki Ishikura"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hixe,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("home"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hra Luoma"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Hydralien"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("IBurmistrov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("icarrion"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ihara"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("iiinn"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Iker AM"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ilya Diallo"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ilya Portnov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Imco Veenstra"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("inalyricalcoma"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Incurious Films"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jack Hill"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jackie Myles"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jacson Spacial Querubin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("James Graham"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("James O'Hare"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("James Thompson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jari-Pekka Kankaanpää"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jarno Lehto"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jaroslav \"Rezza\" Reznik"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jefferson Ietto Novo"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jens Reuterberg"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("João Lima"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Joeri \"Ailaik\" Schouten"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Johan Manders"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("John the Treeman"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("John Urquhart 'Sympodius' Ferguson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jonathan Ringstad"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jonathan Williamson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jörg Rosenbauer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Josep Febrer Salord"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Joshua Ols"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("JP LeBreton,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Juanjo Faico"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("JuanPi Carbajal"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Juan V Camuñas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Jucato"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kahncub Farina"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Karith Densmore"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kārlis Stiģis"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Karlos,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Karl Ove Hufthammer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kathy Reid"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kayne Crinomy"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kerry Mitchell"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kevin \"Hirato\" Meyer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kevin Lariviere"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Klaemoer,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Klas Jonsson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("kokobin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kongorilla"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kpowgames"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Krasi Mirchev"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Kresimir Kis"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lani Aung"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lars Lawrenz"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("LAS,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Laurent"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Laurent Espitallier"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("LcLk"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Leecifer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lee Kenning"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lee Symes"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Leonhard Landrock"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Level¹Imp"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("ligertimjan"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("lili lith,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lilis Iskandar"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lim Yuen Hoe"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Linda van Zoggel-Polman"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lorant Szakacs"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("LordPanther"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lorian Grace"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lucas Falcao,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Luciano Montanaro"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ludovic"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Luiz F. Paulucci"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Lukas Filzer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mads Tuxen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("MahouTskai"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Marc Albrecht"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Marco Caminada"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mario Latronico"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mark Pearson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mark Titchener"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Markus Germann"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Matias Mendiola"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Matthieu Chevillot,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Matt Jordan"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("maxamillion"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Max Torres"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mdk"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("@meffrafax"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("\"Melkesedek\" Jönsson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("memnoch_proxy"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Metalfreak"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael Abrahams,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael Knubben"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael Papkov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael Pohoreski"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michael Thaler"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Michel Vilain"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("micrypt"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mike"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mike"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Linksvayer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("miko"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mitja"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mke"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("mnem"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mr Tonks"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mu57Di3"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Mufeed Al-Hashim"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("myster0n"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nasser Alshammari"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Neko-Maya,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nical"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nick Miller"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nicoguaro"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nicolas Brisset"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nicolas Duhil"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nikolai Schlegel"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nikolaj Woroschilow"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("NiKoZ,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Nils Sabelstrom"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nml.121"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nullreff"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nut-case"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nya"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("nylnook"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Odd Pierrot"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Odysseas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("oenvoyage"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Olle Jonsson,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Oskar Świerad"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Oxben"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pablo Gil"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pascal Schmid"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pat David"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Patrick \"ponpat\" Poniewas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Paul Wortmann"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pawel"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Swierczynski"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("P+B-Snegge"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Peter Moonen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Peter Simonsson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pete Smith"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pevzi"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Philip Cohn-Cort"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Philip Edwards (@p2edwards)"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Pierre Dumot"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("pKrime"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("pnlarsson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Ponpon malon"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rafał Danhoffer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rainer Gievers"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("RayoGlauco,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("RealZero"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Reinhard"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rhakios"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Richard Bensley"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Richard Jarvis"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rick Stirling"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("ridli"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Robert Wloch Professional Consulting"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Robin Princeley"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rodrigo Hobart García"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Roland"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Roman Nazarenko"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Rubén Moreno Montoliu"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Sam Alarcón"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Samuel Roberts"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Scott Petrovic,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Scott Wilson"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("SeaJey"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("sebokie"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Shawn Rutledge"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Shiruriru"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Silvan Jegen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Simon Legrand"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("S J Bennett"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("S Jester,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Sketch Stick"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Skevos Mavros"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Snoopfilou"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Soares Chen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Soren Lane"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Søren Thing Andersen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Soriac"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stefan Steinbauer"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stephen Croft"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stephen D Egts"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stephen Shiu"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Sternenwolf"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Steven Calwas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stramaz"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stuart"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Stuart Martin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Studio Regen,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Sumanas"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Syndarion"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("tanukisan"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Tasuku Suzuki"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("TD-Linux"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Teddy Ursadorable"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Tepee (alias Tristan Paulais)"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("TesX,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Thomas Beck (plasmasolutions)"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Thomas Penin"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Tim Lawrence"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Todimus"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Tyson Tan"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Usamah Philips"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Utao"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Vinicius Braga"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Vlad"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Vladislav A. Makeev"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("vo hoang"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("voltagex"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("vxmrtm"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Wahooney"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Wilhansen Joseph Li"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Will Thorup,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Wohma4"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Wybren van Keulen"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Xavier Guillot"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("xghostx7"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Yalyn \"Yabo\" Vinkindo"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Yuriy Chernyshov"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Zatapathique,"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Zett-0"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("Zorael"), i18n("Krita 2.9 Kickstarter Backer"));
    aboutData->addCredit(i18n("And 47 anonymous backers"), i18n("Krita 2.9 Kickstarter Backer"));


    return aboutData;
}

