/* config-tiles.h.  Generated by cmake from config-tiles.h.cmake */

/* Define if you are using the 'old' (Krita 1.5+-style) or 'new' (post-2.O-style) of tile system */
#cmakedefine USE_OLD_TILESYSTEM 1

