/* config-tiles.h.  Generated by cmake from config-tiles.h.cmake */

/* Define if you are using the 'old' (Krita 1.5+-style) or 'new' (post-2.O-style) of tile system */
/**
 * 1 - image/tiles
 * 2 - image/tiles_new
 * 3 - image/tiles3
 */
#ifndef CONFIG_TILES_H_
#define CONFIG_TILES_H_


#ifndef USE_TILESYSTEM
#cmakedefine USE_TILESYSTEM @USE_TILESYSTEM@
#endif


#if USE_TILESYSTEM == 1
#error "The tiles1 backend is not available anymore"
#elif USE_TILESYSTEM == 2
#error "The tiles_new backend is not available anymore"
#elif USE_TILESYSTEM == 3
  #include <tiles3/kis_tiled_data_manager.h>
  #include <tiles3/kis_memento.h>
#endif

#endif /* CONFIG_TILES_H_ */
