/* config-tiles.h.  Generated by cmake from config-tiles.h.cmake */

/* Define if you are using the 'old' (Krita 1.5+-style) or 'new' (post-2.O-style) of tile system */
/**
 * 0 - image/tiles
 * 1 - image/tiles_new
 * 3 - image/tiles3
 */
#ifndef CONFIG_TILES_H_
#define CONFIG_TILES_H_


#ifndef USE_TILESYSTEM
#cmakedefine USE_TILESYSTEM @USE_TILESYSTEM@
#endif


#if USE_TILESYSTEM == 0
  #define TILES_DIR(file) <tiles/file>
#elif USE_TILESYSTEM == 1
  #define TILES_DIR(file) <tiles_new/file>
#elif USE_TILESYSTEM == 3
  #define TILES_DIR(file) <tiles3/file>
#endif


#endif /* CONFIG_TILES_H_ */
