<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="Magnetic Selection Tool">
    <text>Magnetic Selection Tool</text>
  </Actions>
</ActionCollection>
