<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
    <Action name="KisToolSelectSimilar">
      <icon>tool_similar_selection</icon>
      <text>Similar Color Selection Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Similar Color Selection Tool</toolTip>
      <iconText>Similar Color Selection Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
