<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
<text>Tool Shortcuts</text>
<Action name="KisToolSelectOutline">
      <icon>tool_outline_selection</icon>
      <text>Freehand Selection Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Freehand Selection Tool</toolTip>
      <iconText>Freehand Selection Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
