<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
    <Action name="KisToolSelectElliptical">
      <icon>tool_elliptical_selection</icon>
      <text>Elliptical Selection Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Elliptical Selection Tool</toolTip>
      <iconText>Elliptical Selection Tool</iconText>
      <shortcut>J</shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
