<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
        <Action name="KisToolSelectContiguous">
      <icon>tool_contiguous_selection</icon>
      <text>Contiguous Selection Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Contiguous Selection Tool</toolTip>
      <iconText>Contiguous Selection Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
