<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="Rectangular Selection Tool">
    <text>Rectangular Selection Tool</text>
  </Actions>
</ActionCollection>
