/* WARNING! All changes made in this file will be lost! Run 'generate_parser_code.sh' instead. */
static const char* _tokens[] = {
    "AND",
    "AS",
    "ASC",
    "BY",
    "CREATE",
    "DESC",
    "FROM",
    "IN",
    "INTEGER",
    "IS",
    "JOIN",
    "LEFT",
    "LIKE",
    "NOT",
    "NULL",
    "ON",
    "OR",
    "ORDER",
    "RIGHT",
    "SELECT",
    "SIMILAR",
    "TABLE",
    "WHERE",
    "XOR",
    0
};
