#!/bin/sh

if [ -z $1 ]; then
    echo "Usage: $0 NEW_I18N_FILENAME"
    exit 1
fi


CURRENT_FILE=~/web/build/krita-3.0-l10n-win-current.tar.gz
NEW_FILE=~/web/build/$1

if [ ! -f $NEW_FILE ]; then
    echo "File not exists: $NEW_FILE"
    exit 2
fi

if [ -e $CURRENT_FILE ]; then
    rm $CURRENT_FILE
fi

ln -s $NEW_FILE $CURRENT_FILE

