#include <QList>
#include <QString>
#include <QVariant>
#include <QMap>
#include <QByteArray>
#include <QAction>

class Action;
class Canvas;
class Channel;
class ColorDepth;
class ColorManager;
class ColorModel;
class ColorProfile;
class DockWidget;
class DockWidgetFactoryBase;
class Document;
class Filter;
class Generator;
class InfoObject;
class Krita;
class Node;
class Notifier;
class Resource;
class Selection;
class View;
class ViewExtension;
class Window;
