action_classes = ['newaction.newaction.NewAction',
                  'openaction.openaction.OpenAction',
                  'reloadaction.reloadaction.ReloadAction',
                  'saveaction.saveaction.SaveAction',
                    'saveasaction.saveasaction.SaveAsAction',
                  'runaction.runaction.RunAction',
                  'settingsaction.settingsaction.SettingsAction',
                  'debugaction.debugaction.DebugAction',
                  'closeaction.closeaction.CloseAction',
                  'filechangedaction.filechangedaction.FileChangedAction']
