<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Recorder">
  <Actions category="Recorder">
    <text>Recorder</text>
    <Action name="recorder_record_toggle">
      <iconText>Record Timelapse</iconText>
      <text>Record Timelapse</text>
      <toolTip>Record Timelapse</toolTip>
      <shortcut/>
      <icon>media-record</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>true</isCheckable>
    </Action>
    <Action name="recorder_export">
      <iconText>Export Timelapse...</iconText>
      <toolTip>Export Timelapse...</toolTip>
      <text>Export Timelapse...</text>
      <shortcut/>
      <icon>document-export</icon>
      <whatsThis/>
      <statusTip/>
      <isCheckable>false</isCheckable>
    </Action>
    </Actions>
</ActionCollection>
