/* config-memory-leak-tracker.h.  Generated by cmake from config-memory-leak-tracker.h.cmake */

#ifndef CONFIG_MEMORY_LEAK_TRACKER_H_
#define CONFIG_MEMORY_LEAK_TRACKER_H_

#ifndef HAVE_MEMORY_LEAK_TRACKER
#cmakedefine HAVE_MEMORY_LEAK_TRACKER @HAVE_MEMORY_LEAK_TRACKER@
#endif

#ifndef HAVE_BACKTRACE_SUPPORT
#cmakedefine HAVE_BACKTRACE_SUPPORT @HAVE_BACKTRACE_SUPPORT@
#endif


#endif
