#ifndef KISSELECTIONTAGS_H
#define KISSELECTIONTAGS_H


enum SelectionMode {
    PIXEL_SELECTION,
    SHAPE_PROTECTION
};

enum SelectionAction {
    SELECTION_REPLACE,
    SELECTION_ADD,
    SELECTION_SUBTRACT,
    SELECTION_INTERSECT,
    SELECTION_DEFAULT
};

#endif // KISSELECTIONTAGS_H
