<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
    <text>Tool Shortcuts</text>
   <Action name="KisToolPolygon">
      <icon>krita_tool_polygon</icon>
      <text>Polygon Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Polygon Tool. Shift-mouseclick ends the polygon.</toolTip>
      <iconText>Polygon Tool. Shift-mouseclick ends the polygon.</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
