<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
     <Action name="KisToolPath">
      <icon>krita_draw_path</icon>
      <text>Bezier Curve Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Bezier Curve Tool. Shift-mouseclick or double-click ends the curve.</toolTip>
      <iconText>Bezier Curve Tool. Shift-mouseclick or double-click ends the curve.</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
