<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Krita">
  <Actions category="Filters">
    <text context="Filter as an effect">Filters</text>
    <Action name="krita_filter_height to normal">
      <icon/>
      <text>Height to Normal Map Filter</text>
      <whatsThis></whatsThis>
      <toolTip>Height to Normal Map Filter</toolTip>
      <iconText>Height to Normal Map Filter</iconText>
      <activationFlags>10000</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
