#include <QObject>
#include <QThread>
#include <QtConcurrent>
#include <QList>
#include <QVector>
#include <QVariant>
#include <QPainter>
#include <kis_types.h>
#include <kis_debug.h>
#include <kis_global.h>
