<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
    <text>Tool Shortcuts</text>
        <Action name="KisAssistantTool">
      <icon>krita_tool_assistant</icon>
      <text>Assistant Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Assistant Tool</toolTip>
      <iconText>Assistant Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
