FIND_PATH(SPNAV_INCLUDE_DIR spnav.h /usr/include/ /usr/local/include/)

FIND_LIBRARY(SPNAV_LIBRARY NAMES spnav PATH /usr/lib /usr/local/lib) 

IF (SPNAV_INCLUDE_DIR AND SPNAV_LIBRARY)
   SET(SPNAV_FOUND TRUE)
ENDIF (SPNAV_INCLUDE_DIR AND SPNAV_LIBRARY)


IF (SPNAV_FOUND)
   IF (NOT Spnav_FIND_QUIETLY)
      MESSAGE(STATUS "Found Spnav: ${SPNAV_LIBRARY}")
   ENDIF (NOT Spnav_FIND_QUIETLY)
ELSE (SPNAV_FOUND)
   IF (Spnav_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Spnav")
   ENDIF (Spnav_FIND_REQUIRED)
ENDIF (SPNAV_FOUND)