<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Krita">
  <Actions category="Krita">
     <text>S-Pen Actions</text>

     <Action name="spen_click">
       <icon></icon>
       <text>S-Pen Button Click</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut>@</shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>

    <Action name="spen_double_click">
       <icon></icon>
       <text>S-Pen Button Double Click</text>
       <whatsThis></whatsThis>
       <toolTip></toolTip>
       <iconText></iconText>
       <activationFlags>10000</activationFlags>
       <activationConditions>0</activationConditions>
       <shortcut>#</shortcut>
       <isCheckable>false</isCheckable>
       <statusTip></statusTip>
     </Action>

    <Action name="spen_swipe_up">
        <icon></icon>
        <text>S-Pen Gesture Swipe Up</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>F7</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
      </Action>

    <Action name="spen_swipe_down">
          <icon></icon>
          <text>S-Pen Gesture Swipe Down</text>
          <whatsThis></whatsThis>
          <toolTip></toolTip>
          <iconText></iconText>
          <activationFlags>10000</activationFlags>
          <activationConditions>0</activationConditions>
          <shortcut>F8</shortcut>
          <isCheckable>false</isCheckable>
          <statusTip></statusTip>
        </Action>

<Action name="spen_swipe_left">
    <icon></icon>
    <text>S-Pen Gesture Swipe Left</text>
    <whatsThis></whatsThis>
    <toolTip></toolTip>
    <iconText></iconText>
    <activationFlags>10000</activationFlags>
    <activationConditions>0</activationConditions>
    <shortcut>F9</shortcut>
    <isCheckable>false</isCheckable>
    <statusTip></statusTip>
  </Action>

<Action name="spen_swipe_right">
    <icon></icon>
    <text>S-Pen Gesture Swipe Right</text>
    <whatsThis></whatsThis>
    <toolTip></toolTip>
    <iconText></iconText>
    <activationFlags>10000</activationFlags>
    <activationConditions>0</activationConditions>
    <shortcut>F10</shortcut>
    <isCheckable>false</isCheckable>
    <statusTip></statusTip>
  </Action>

<Action name="spen_circle_cw">
    <icon></icon>
    <text>S-Pen Gesture Circle Clockwise</text>
    <whatsThis></whatsThis>
    <toolTip></toolTip>
    <iconText></iconText>
    <activationFlags>10000</activationFlags>
    <activationConditions>0</activationConditions>
    <shortcut>F11</shortcut>
    <isCheckable>false</isCheckable>
    <statusTip></statusTip>
  </Action>

    <Action name="spen_circle_ccw">
        <icon></icon>
        <text>S-Pen Gesture Circle Counter-Clockwise</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>F12</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
    </Action>

<Action name="spen_show_popup_palette">
    <icon></icon>
    <text>Toggle popup palette with S-Pen</text>
    <whatsThis></whatsThis>
    <toolTip></toolTip>
    <iconText></iconText>
    <activationFlags>10000</activationFlags>
    <activationConditions>0</activationConditions>
    <shortcut></shortcut>
    <isCheckable>false</isCheckable>
    <statusTip></statusTip>
</Action>
  </Actions>
</ActionCollection>
