/* krita_xsimd_macos_workaround.h.  Generated by cmake from krita_xsimd_macos_workaround.h.cmake */

/* Define if we should disable XSIMD implementation of KoClipMaskPainter (usually for macOS) */
#cmakedefine DISABLE_CLIP_MASK_PAINTER_ON_MACOS 1
